'use strict';
// Aggregates only: no dictated text is fetched or displayed by this dashboard.
(()=>{
  const root=document.createElement('div');root.className='voice-statistics';
  root.innerHTML=`<div class="voice-card"><span class="voice-eyebrow">YOUR WORDS, AT A GLANCE</span><h2>把表达交给声音</h2><dl class="voice-stat-grid"><div><dt>今日输入</dt><dd id="vs-today">0<small>字</small></dd></div><div><dt>本月输入</dt><dd id="vs-month">0<small>字</small></dd></div></dl><div class="voice-stat-strip" id="vs-summary"></div><p class="voice-stat-empty" id="vs-empty">完成第一段听写后，这里会记录你的表达。只统计斐墨语音，不记录其他输入法。</p></div>
  <div class="voice-card"><div class="voice-chart-head"><h2>输入字数趋势</h2><select id="vs-period" aria-label="趋势周期"><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select></div><div class="voice-bars" id="vs-bars" aria-label="每日语音输入字数"></div><div class="voice-chart-axis" id="vs-axis"></div><div class="voice-chart-detail" id="vs-bar-detail" aria-live="polite">选择一天，查看输入字数与听写次数。</div></div>
  <div class="voice-card"><div class="voice-chart-head"><h2>表达热力图</h2><select id="vs-year" aria-label="热力图年份"></select></div><div class="voice-heatmap-scroll"><div class="voice-heatmap" id="vs-heatmap" aria-label="全年每日语音输入热力图"></div></div><div class="voice-heatmap-legend"><span id="vs-year-range"></span><span>浅 → 深 · 输入字数</span></div><div class="voice-chart-detail" id="vs-heat-detail" aria-live="polite">选择日期查看统计。</div><p class="voice-stat-empty">仅保存每日字数、时长、次数；字数包含汉字、字母和数字，不包含标点与空白。统计从本版更新后开始。</p></div>`;
  document.querySelector('[data-voice-section=dictation]').prepend(root);
  const $=id=>document.getElementById(id),key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,fmt=n=>Number(n||0).toLocaleString('zh-CN');let stats=null;
  const describe=d=>`${d.key} · ${fmt(d.chars)} 字 · ${d.sessions||0} 次听写 · ${Math.round((d.seconds||0)/60)} 分钟`;
  const day=(map,d)=>({key:key(d),chars:0,seconds:0,sessions:0,...map.get(key(d))});
  function bars(){if(!stats)return;const count=Number($('vs-period').value),map=new Map(stats.days.map(d=>[d.key,d]));const rows=Array.from({length:count},(_,i)=>{const d=new Date();d.setDate(d.getDate()-count+1+i);return day(map,d)}),max=Math.max(1,...rows.map(d=>d.chars));$('vs-bars').replaceChildren();for(const d of rows){const b=document.createElement('button');b.className='voice-bar';b.title=describe(d);b.setAttribute('aria-label',describe(d));const i=document.createElement('i');i.style.setProperty('--height',`${Math.max(3,100*d.chars/max)}%`);b.append(i);const show=()=>{$('vs-bar-detail').textContent=describe(d)};b.onclick=show;b.onfocus=show;b.onmouseenter=show;$('vs-bars').append(b);}$('vs-axis').replaceChildren(...[rows[0].key.slice(5),'今天'].map(t=>{const s=document.createElement('span');s.textContent=t;return s}));}
  function heatmap(){if(!stats)return;const year=Number($('vs-year').value),map=new Map(stats.days.map(d=>[d.key,d])),max=Math.max(1,...stats.days.filter(d=>d.key.startsWith(year+'-')).map(d=>d.chars));const grid=$('vs-heatmap');grid.replaceChildren();const start=new Date(year,0,1),end=new Date(year+1,0,1);for(let i=0;i<start.getDay();i++){const s=document.createElement('span');s.setAttribute('aria-hidden','true');grid.append(s);}for(let dt=new Date(start);dt<end;dt.setDate(dt.getDate()+1)){const d=day(map,dt),b=document.createElement('button');b.dataset.level=d.chars?String(Math.min(4,Math.ceil(4*d.chars/max))):'0';b.title=describe(d);b.setAttribute('aria-label',describe(d));const show=()=>{$('vs-heat-detail').textContent=describe(d)};b.onclick=show;b.onfocus=show;b.onmouseenter=show;grid.append(b);}$('vs-year-range').textContent=year+' · 1 月 — 12 月';const scroll=grid.parentElement;scroll.scrollLeft=year===new Date().getFullYear()?Math.max(0,((Date.now()-start)/86400000/7)*13-scroll.clientWidth+26):0;}
  function render(s){if(!s?.days)return;stats=s;$('vs-today').firstChild.textContent=fmt(s.today.chars);$('vs-month').firstChild.textContent=fmt(s.month.chars);$('vs-summary').replaceChildren();for(const [n,label]of[[fmt(s.total.chars),'累计字数'],[s.activeDays,'活跃天数'],[Math.round(s.total.seconds/60),'听写分钟'],[s.speed,'字 / 分钟']]){const span=document.createElement('span'),b=document.createElement('b');b.textContent=n;span.append(b,document.createTextNode(label));$('vs-summary').append(span);}$('vs-empty').hidden=s.total.sessions>0;const previous=$('vs-year').value,years=[...new Set([new Date().getFullYear(),...s.days.map(d=>Number(d.key.slice(0,4)))])].sort((a,b)=>b-a);$('vs-year').replaceChildren(...years.map(y=>new Option(String(y),String(y))));if(years.includes(Number(previous)))$('vs-year').value=previous;bars();heatmap();}
  $('vs-period').onchange=bars;$('vs-year').onchange=heatmap;
  window.VoiceStatistics={refresh:async()=>render(await window.api.voiceStats()),render};window.api.onVoiceStatsChanged(render);
})();
