'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');const {FileLibrary,safeName}=require('../lib/file-library');const {parseLrc}=require('../lib/lyrics');
function setup(t,classify){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'feimo-archive-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {dir,lib:new FileLibrary({dir,classify,ocr:async()=>({lines:[{text:'Image document'}]})})};}
test('AI classification stores a copy into an existing folder, preserves originals and avoids overwriting',async t=>{let data;const {dir,lib}=setup(t,async d=>{data=d;return {projectId:project.id,folderId:folder.id};});const project=await lib.create({name:'Design'}),folder=await lib.create({projectId:project.id,name:'Briefs'}),src=path.join(dir,'brief.txt');fs.writeFileSync(src,'Fictional design brief');await lib.import([src]);await lib.import([src]);assert.equal(data.content,'Fictional design brief');assert.equal(fs.readFileSync(src,'utf8'),'Fictional design brief');assert.equal(lib.data.files.length,2);assert.ok(lib.data.files.some(x=>x.name==='brief (1).txt'));for(const f of lib.data.files)assert.equal(fs.readFileSync(lib.pathFor(f.id),'utf8'),'Fictional design brief');assert.ok(!JSON.stringify(lib.view().files).includes(dir));});
test('unknown binary formats ask for a project, decide creates suggested categories, pending requests survive restart',async t=>{const {dir,lib}=setup(t,async d=>{assert.equal(d.content,'');return {projectName:'Audio',folderName:'Samples',reason:'A sound sample'};});const src=path.join(dir,'sample.wav');fs.writeFileSync(src,Buffer.from([0,1,2,3]));await lib.import([src]);assert.equal(lib.view().pending.length,1);const reopened=new FileLibrary({dir,classify:async()=>({}),ocr:async()=>{}});assert.equal(reopened.view().pending.length,1);const id=reopened.view().pending[0].id;await reopened.resolve({id,decide:true});assert.equal(reopened.data.projects[0].name,'Audio');assert.equal(reopened.data.projects[0].folders[0].name,'Samples');assert.deepEqual(fs.readFileSync(reopened.pathFor(id)),Buffer.from([0,1,2,3]));assert.equal(new FileLibrary({dir}).view().pending.length,0);});
test('classification errors preserve staged data, manual new project/folder and cancellation work',async t=>{const {dir,lib}=setup(t,async()=>{throw Error('Offline');});const src=path.join(dir,'note.md');fs.writeFileSync(src,'Test');await lib.import([src]);const id=lib.view().pending[0].id;assert.match(lib.view().pending[0].reason,/Offline/);await lib.resolve({id,projectName:'Notes',folderName:'Inbox'});await lib.import([src]);await lib.resolve({id:lib.view().pending[0].id,cancel:true});assert.equal(lib.view().pending.length,0);assert.equal(fs.readdirSync(lib.stage).length,0);assert.ok(fs.existsSync(src));});
test('paths reject traversal and invalid category identifiers; duplicates reuse existing categories',async t=>{const {lib}=setup(t,async()=>({}));assert.equal(safeName('../unsafe'),'.._unsafe');assert.equal(safeName('CON'),'_CON');assert.throws(()=>safeName(''));const p=await lib.create({name:'Notes'});assert.equal((await lib.create({name:'Notes'})).id,p.id);assert.throws(()=>lib.location('../escape'));lib.data.files.push({id:'bad',path:'../escape'});assert.throws(()=>lib.pathFor('bad'));});
test('LRC parses multiple timestamps and fractional seconds without displaying metadata',()=>{const result=parseLrc('[ar:Demo]\n[00:01.20][00:03.50]Hello\n[01:00]World');assert.deepEqual(result,[{time:1.2,text:'Hello'},{time:3.5,text:'Hello'},{time:60,text:'World'}]);});
test('content search and explicit file context use stored excerpts without returning private paths',async t=>{const {dir,lib}=setup(t,async()=>({projectName:'Notes',folderName:'Research'}));const src=path.join(dir,'note.txt');fs.writeFileSync(src,'The fictional project uses progressive blur.');await lib.import([src]);const id=lib.view().pending[0].id;await lib.resolve({id,decide:true});const results=lib.search('progressive');assert.equal(results.length,1);assert.equal(results[0].id,id);assert.match(results[0].snippet,/progressive/);assert.equal(lib.context([id])[0].content,'The fictional project uses progressive blur.');assert.throws(()=>lib.context(['missing']));assert.throws(()=>lib.context(Array(7).fill(id)));assert.ok(!JSON.stringify(lib.view().files).includes('The fictional project'));assert.ok(!JSON.stringify(results).includes(dir));});
