'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {Toolbox,sensitive}=require('../lib/toolbox');
const {quotaCard,QuotaAlerts}=require('../lib/prompt-cards');
const colors=require('../renderer/shared/colors');
function store(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'feimo-tools-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const key=crypto.randomBytes(32);const codec={encrypt:v=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(v),c.final(),c.getAuthTag()]);},decrypt:b=>{const d=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString();}};return {file:path.join(dir,'toolbox.bin'),codec};}
test('工具箱加密落盘，重启恢复速记和剪贴板，重复收录去重',t=>{const s=store(t),a=new Toolbox(s.file,s.codec);a.capture({kind:'text',text:'个人的速记内容'});a.capture({kind:'text',text:'个人的速记内容'});a.saveNote({text:'秘密草稿'});assert.equal(a.view().clips.length,1);assert.ok(!fs.readFileSync(s.file).includes(Buffer.from('秘密草稿')));const b=new Toolbox(s.file,s.codec);assert.equal(b.view().notes[0].text,'秘密草稿');assert.equal(b.capture({kind:'text',text:'个人的速记内容'},true).status,'saved');assert.equal(b.capture({kind:'text',text:'个人的速记内容'},true).status,'unchanged');});
test('常见密钥拒绝入历史，清空保留固定项，历史有上限',t=>{const s=store(t),a=new Toolbox(s.file,s.codec);assert.equal(a.capture({kind:'text',text:'ntn_'+ 'A'.repeat(28)}).status,'sensitive');assert.ok(sensitive('api_key = '+ 'q'.repeat(24)));assert.ok(!sensitive('今天需要整理 token 用量'));const {id}=a.capture({kind:'text',text:'固定内容'});a.editClip(id,'pin');for(let i=0;i<90;i++)a.capture({kind:'text',text:'复制内容 '+i});assert.equal(a.view().clips.length,80);a.clearClips();assert.equal(a.view().clips[0].value,'固定内容');assert.equal(a.view().clips.length,1);});
test('坏密文不可覆盖，速记与色卡输入有边界',t=>{const s=store(t);fs.writeFileSync(s.file,'broken');assert.throws(()=>new Toolbox(s.file,s.codec),/解密/);assert.equal(fs.readFileSync(s.file,'utf8'),'broken');fs.unlinkSync(s.file);const a=new Toolbox(s.file,s.codec);assert.throws(()=>a.saveNote({text:''}));assert.throws(()=>a.savePalette({colors:['bad','#FFFFFF']}));a.savePalette({name:'雾林',colors:['#789A87','#FFFFFF']});a.savePalette({name:'新名',colors:['#789a87','#ffffff']});assert.equal(a.view().palettes.length,1);});
test('配色转换正确，黑白对比 21:1，主色保留，HEX 校验',()=>{assert.equal(colors.contrast('#000000','#FFFFFF'),21);for(const base of ['#789A87','#000000','#FFFFFF','#FF0000']){assert.equal(colors.hex(...colors.hsl(base)),base);for(const mode of ['analogous','triadic','complementary']){const list=colors.harmony(base,mode);assert.equal(list[1],base);assert.ok(list.every(c=>/^#[A-F0-9]{6}$/.test(c)));}}assert.throws(()=>colors.harmony('#xxx'));});
test('Codex 额度只采用有效观测值，阈值与重置去重',()=>{const now=Date.now(),a=new QuotaAlerts();const limits={observedAt:new Date(now).toISOString(),primary:{usedPercent:81,windowMinutes:300,resetsAt:Math.floor(now/1000)+5000},secondary:null};assert.ok(a.next(limits,now));assert.equal(a.next(limits,now),null);assert.ok(a.next({...limits,primary:{...limits.primary,usedPercent:96}},now));assert.equal(quotaCard({...limits,observedAt:new Date(now-86400001).toISOString()},now),null);assert.equal(quotaCard({...limits,primary:{usedPercent:null}},now),null);assert.equal(quotaCard({...limits,primary:{...limits.primary,resetsAt:Math.floor(now/1000)-1}},now),null);});
