'use strict';
(()=>{
 const api=window.api,root=document.getElementById('study-soundscape'),$=id=>root.querySelector('#'+id);let state,category='all',query='';
 root.innerHTML='<div class="card noise-library-hero"><div><p class="tool-meta">闪念上岸 · Moodist</p><h2>把世界调低一点</h2><p>自然、雨声与城市声景，最多混合三个声音。</p></div></div><div class="card"><div class="noise-library-controls"><button class="btn primary" id="ns-play">播放</button><select id="ns-preset" aria-label="声景预设"></select><span id="ns-status" class="tool-meta" role="status"></span></div><div id="ns-tracks"></div></div><div class="card"><h3>声音资料库</h3><input id="ns-search" class="tool-search" placeholder="搜索声音…" aria-label="搜索声音"><div class="noise-categories" id="ns-categories"></div><div class="noise-library-grid" id="ns-library"></div><p class="tool-meta">音源来自网站的 Moodist 目录，在线加载。音频许可为 Pixabay / CC0，详见项目素材说明。</p></div>';
 async function command(data){try{render(await api.soundscapeCommand(data))}catch(e){UI.toast(e.message,true)}}
 function library(){const list=$('ns-library');list.replaceChildren();for(const sound of state.catalog.sounds.filter(s=>(category==='all'||category===s.category)&&(!query||(s.name+' '+s.description).toLowerCase().includes(query)))){const selected=state.tracks.some(t=>t.id===sound.id),b=document.createElement('button');b.className='noise-sound'+(selected?' selected':'');b.setAttribute('aria-pressed',String(selected));const icon=window.ReiconFilled.create(selected?'CheckCircle':'Music',20),name=document.createElement('span');name.textContent=sound.name;b.append(icon,name);b.title=state.catalog.categories[sound.category]+' · '+sound.quality;b.onclick=()=>{if(!selected&&state.tracks.length===3){UI.toast('最多混合三个声音，请先移除一个声音');return}command({tracks:selected?state.tracks.filter(t=>t.id!==sound.id):[...state.tracks,{id:sound.id,volume:.5}]})};list.append(b)}if(!list.children.length)list.textContent='没有匹配的声音';}
 function render(value){if(!value?.catalog)return;state=value;if(!$('ns-preset').options.length){for(const mix of state.catalog.mixes){const o=document.createElement('option');o.value=mix.id;o.textContent=mix.name;$('ns-preset').append(o)}const o=document.createElement('option');o.value='custom';o.textContent='我的混音';$('ns-preset').append(o);
 for(const [id,label] of [['all','全部'],...Object.entries(state.catalog.categories)]){const b=document.createElement('button');b.className='btn small';b.dataset.category=id;b.textContent=label;b.onclick=()=>{category=id;library();for(const button of $('ns-categories').children)button.classList.toggle('primary',button===b)};$('ns-categories').append(b)}}
 $('ns-preset').value=state.catalog.mixes.find(m=>m.name===state.name)?.id||'custom';$('ns-play').textContent=state.playing?'暂停':'播放';$('ns-play').disabled=!state.tracks.length;$('ns-status').textContent=state.error||(state.loading?'正在加载…':state.playing?'正在播放 · 关闭工作台后继续':'已暂停');SoundscapeUI.tracks($('ns-tracks'),state,command,{removable:true});library();
 }
 $('ns-play').onclick=()=>command({playing:!state?.playing});$('ns-preset').onchange=()=>{if($('ns-preset').value!=='custom')command({preset:$('ns-preset').value})};$('ns-search').oninput=()=>{query=$('ns-search').value.trim().toLowerCase();if(state)library()};api.onSoundscapeChanged?.(render);api.soundscapeState?.().then(render);
})();
