'use strict';
const path=require('node:path'),fs=require('node:fs'),{spawn}=require('node:child_process');
const {imageBuffer}=require('./capture-vision'),{writeImageVerified,writeTextVerified}=require('./clipboard');
class CaptureHost{
 constructor({electron,dir,settings,vision,toolbox,changed,overlays}){Object.assign(this,{electron,dir,settings,vision,toolbox,changed,overlays});this.windows=new Map();this.hidden=[];this.active=false;this.popup=null;this.stopping=false;}
 async start(){if(this.active)return;this.popup?.hide();this.active=true;this.hidden=this.overlays().filter(w=>w&&!w.isDestroyed()&&w.isVisible());for(const w of this.hidden)w.hide();
  try{await new Promise(r=>setTimeout(r,100));const displays=this.electron.screen.getAllDisplays(),size={width:Math.max(...displays.map(d=>Math.ceil(d.size.width*d.scaleFactor))),height:Math.max(...displays.map(d=>Math.ceil(d.size.height*d.scaleFactor)))};
   const sources=await this.electron.desktopCapturer.getSources({types:['screen'],thumbnailSize:size,fetchWindowIcons:false});if(this.stopping)return;
   for(const display of displays){const source=sources.find(s=>s.display_id===String(display.id));if(!source||source.thumbnail.isEmpty())continue;const w=this.window('screenshot.html',{...display.bounds,focusable:true});this.windows.set(w,{image:source.thumbnail.toDataURL(),displayId:display.id});w.on('closed',()=>{this.windows.delete(w);if(!this.windows.size&&this.active)this.finish();});await w.loadFile(path.join(__dirname,'../renderer/capture/screenshot.html'));w.showInactive();}
   if(!this.windows.size)throw Error('无法获取屏幕截图');const pointer=this.electron.screen.getCursorScreenPoint(),display=this.electron.screen.getDisplayNearestPoint(pointer);const preferred=[...this.windows].find(([,d])=>d.displayId===display.id)?.[0];preferred?.focus();
  }catch(e){this.finish();throw e;}
 }
 window(file,bounds){const w=new this.electron.BrowserWindow({show:false,frame:false,transparent:true,backgroundColor:'#00000000',hasShadow:false,skipTaskbar:true,resizable:false,alwaysOnTop:true,...bounds,webPreferences:{preload:path.join(__dirname,'../preload/capture-preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false,backgroundThrottling:false}});w.setAlwaysOnTop(true,'screen-saver');w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',e=>e.preventDefault());return w;}
 finish(){this.controller?.abort();this.controller=null;this.active=false;const windows=[...this.windows.keys()];this.windows.clear();for(const w of windows)if(!w.isDestroyed())w.destroy();for(const w of this.hidden.splice(0))if(!w.isDestroyed()&&!this.stopping)w.showInactive();}
 async showClipboard(){if(this.active||this.settings.get('toolbox',{}).middleHold===false)return;const {screen}=this.electron,p=screen.getCursorScreenPoint(),a=screen.getDisplayNearestPoint(p).workArea,width=Math.min(370,a.width),height=Math.min(490,a.height);const bounds={x:Math.round(Math.max(a.x,Math.min(p.x-20,a.x+a.width-width))),y:Math.round(Math.max(a.y,Math.min(p.y+12,a.y+a.height-height))),width,height};
  if(!this.popup||this.popup.isDestroyed()){this.popup=this.window('clipboard.html',{...bounds,focusable:false});this.popup.on('blur',()=>this.popup?.hide());await this.popup.loadFile(path.join(__dirname,'../renderer/capture/clipboard.html'));}else{this.popup.setFocusable(false);this.popup.setBounds(bounds);await this.popup.webContents.reload();}this.popup.showInactive();
 }
 register(){const {ipcMain:ipc,clipboard,ClipboardItem,dialog}=this.electron;
  const handle=(name,fn)=>ipc.handle(name,async(e,...args)=>{const win=[...this.windows.keys()].find(w=>w.webContents===e.sender)|| (this.popup?.webContents===e.sender?this.popup:null);if(!win)throw Error('此窗口不能进行截图操作');return fn(win,...args);});
  handle('capture:init',win=>this.windows.get(win)||{popup:true});handle('capture:cancel',win=>{if(win===this.popup)win.hide();else this.finish();return true;});
  handle('capture:select',win=>{for(const other of this.windows.keys())if(other!==win)other.hide();return true;});
  handle('capture:commit',async(win,image)=>{if(win===this.popup)throw Error('请选择截图');imageBuffer(image);await writeImageVerified(clipboard,ClipboardItem,image);const r=this.toolbox().capture({kind:'image',dataUrl:image});if(r.status==='saved')this.changed();this.finish();return r;});
  handle('capture:save',async(win,image)=>{const bytes=imageBuffer(image),r=await dialog.showSaveDialog(win,{defaultPath:'斐墨截图-'+new Date().toISOString().replace(/[:.]/g,'-')+'.png',filters:[{name:'PNG 图片',extensions:['png']}]});if(r.canceled)return false;await fs.promises.writeFile(r.filePath,bytes);return true;});
  handle('capture:extract',async(win,data)=>{if(!this.windows.has(win))throw Error('请选择截图');if(this.controller)throw Error('正在处理当前截图');const controller=new AbortController();this.controller=controller;try{return await this.vision.extract({...data,signal:controller.signal});}finally{if(this.controller===controller)this.controller=null;}});
  handle('capture:copyText',async(_win,text)=>{if(typeof text!=='string'||text.length>100000)throw Error('文字过长');await writeTextVerified(clipboard,text);return true;});
  handle('capture:clips',win=>{if(win!==this.popup)throw Error('此窗口不能读取历史');return this.toolbox().view().clips;});
  handle('capture:copyClip',async(win,id)=>{if(win!==this.popup)throw Error('此窗口不能读取历史');const clip=this.toolbox().data.clips.find(c=>c.id===id);if(!clip)throw Error('记录已不存在');if(clip.kind==='image')await writeImageVerified(clipboard,ClipboardItem,clip.value);else await writeTextVerified(clipboard,clip.value);win.hide();return true;});
  handle('capture:focus',win=>{if(win!==this.popup)return false;win.setFocusable(true);win.focus();return true;});
 }
 startPointer(){if(process.platform!=='win32'||this.pointer)return;const script=require('./native-script').nativeScript(path.join(__dirname,'middle-pointer.ps1'),path.join(this.dir,'native-capture'));this.pointer=spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script],{windowsHide:true,stdio:['ignore','pipe','ignore']});let pending='';this.pointer.stdout.on('data',b=>{pending+=b.toString();let i;while((i=pending.indexOf('\n'))>=0){const line=pending.slice(0,i).trim();pending=pending.slice(i+1);if(line==='hold')void this.showClipboard().catch(()=>{});else if(line==='left')this.outsideClick();}});this.pointer.on('error',()=>{});this.pointer.on('exit',()=>{this.pointer=null;});}
 outsideClick(){if(!this.popup?.isVisible()||this.popup.isDestroyed())return;const p=this.electron.screen.getCursorScreenPoint(),b=this.popup.getBounds();if(p.x<b.x||p.x>b.x+b.width||p.y<b.y||p.y>b.y+b.height)this.popup.hide();}
 stop(){this.stopping=true;this.pointer?.kill();this.finish();this.popup?.destroy();}
}
module.exports={CaptureHost};
