'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const TEXT=new Set(['.txt','.md','.csv','.json','.log','.js','.ts','.py','.html','.css','.xml','.yaml','.yml','.sql','.lrc','.srt']);
const safeName=s=>{const n=String(s||'').normalize('NFC').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'').trim().slice(0,100);if(!n)throw new Error('请填写项目或文件夹名称');return /^(con|prn|aux|nul|com\d|lpt\d)(\.|$)/i.test(n)?'_'+n:n;};
class FileLibrary{
  constructor({dir,classify,ocr,onChange=()=>{},onPrompt=()=>{},onSaved=()=>{}}){Object.assign(this,{classify,ocr,onChange,onPrompt,onSaved});this.root=path.join(dir,'文件库');this.stage=path.join(this.root,'.待归档');this.file=path.join(this.root,'index.json');fs.mkdirSync(this.stage,{recursive:true});this.data={projects:[],files:[]};try{this.data=JSON.parse(fs.readFileSync(this.file,'utf8'));}catch{}this.pending=new Map();for(const r of this.data.pending||[])if(fs.existsSync(r.staged)){r.phase='等待选择';this.pending.set(r.id,r);}this.queue=Promise.resolve();}
  locked(fn){const p=this.queue.then(fn);this.queue=p.catch(()=>{});return p;}
  write(){fs.writeFileSync(this.file+'.tmp',JSON.stringify({...this.data,pending:[...this.pending.values()]},null,2));fs.renameSync(this.file+'.tmp',this.file);this.onChange();}
  view(){return {projects:this.data.projects,files:this.data.files.map(f=>({...f,path:undefined,excerpt:undefined})),pending:[...this.pending.values()].map(({staged,...r})=>r),root:this.root};}
  location(project,folder){const p=this.data.projects.find(x=>x.id===project);if(!p)throw new Error('项目不存在');let result=path.join(this.root,p.directory);if(folder){const f=p.folders.find(x=>x.id===folder);if(!f)throw new Error('文件夹不存在');result=path.join(result,f.directory);}const relative=path.relative(this.root,result);if(relative.startsWith('..')||path.isAbsolute(relative))throw new Error('无效归档路径');return result;}
  async create({projectId,name}){return this.locked(()=>this.createNow(projectId,name));}
  createNow(projectId,name){const clean=safeName(name),id=crypto.randomUUID();let record;if(projectId){const p=this.data.projects.find(x=>x.id===projectId);if(!p)throw new Error('项目不存在');record=p.folders.find(x=>x.name===clean);if(record)return record;record={id,name:clean,directory:clean+'-'+id.slice(0,8)};p.folders.push(record);fs.mkdirSync(this.location(p.id,id),{recursive:true});}else{record=this.data.projects.find(x=>x.name===clean);if(record)return record;record={id,name:clean,directory:clean+'-'+id.slice(0,8),folders:[]};this.data.projects.push(record);fs.mkdirSync(this.location(id),{recursive:true});}this.write();return record;}
  async extract(file){const ext=path.extname(file).toLowerCase(),stat=await fs.promises.stat(file);if(TEXT.has(ext)&&stat.size<=10*1024*1024){const h=await fs.promises.open(file,'r');try{const b=Buffer.alloc(Math.min(stat.size,64000));await h.read(b,0,b.length,0);return {text:b.toString('utf8').slice(0,12000),kind:'文字内容'};}finally{await h.close();}}
    if(ext==='.pdf'&&stat.size<=30*1024*1024){const {PDFParse}=require('pdf-parse'),parser=new PDFParse({data:await fs.promises.readFile(file)});try{return {text:(await parser.getText({first:4})).text.slice(0,12000),kind:'PDF 前四页'};}finally{await parser.destroy();}}
    if(ext==='.docx'&&stat.size<=20*1024*1024)return {text:(await require('mammoth').extractRawText({path:file})).value.slice(0,12000),kind:'文档正文'};
    if(['.png','.jpg','.jpeg','.webp','.bmp','.tiff'].includes(ext)&&stat.size<=30*1024*1024){const d=await this.ocr(file);return {text:d.lines.map(x=>x.text).join('\n').slice(0,12000),kind:'本机图片识别'};}
    return {text:'',kind:'文件名与类型（此格式未读取正文）'};
  }
  async import(paths){if(!Array.isArray(paths)||!paths.length||paths.length>30)throw new Error('一次最多拖入 30 个文件');const results=[];for(const source of paths){const file=path.resolve(String(source)),stat=await fs.promises.stat(file);if(!stat.isFile())throw new Error('请拖入文件，文件夹请在文件库创建');if(stat.size>1024*1024*1024)throw new Error('单个文件最多支持 1 GB');const id=crypto.randomUUID(),name=safeName(path.basename(file)),staged=path.join(this.stage,id+path.extname(name));await fs.promises.copyFile(file,staged,fs.constants.COPYFILE_EXCL);const r={id,name,size:stat.size,staged,phase:'识别中',suggestion:null};this.pending.set(id,r);this.write();try{const extracted=await this.extract(staged);r.kind=extracted.kind;r.excerpt=extracted.text;const choice=await this.classify({name,size:r.size,content:extracted.text,projects:this.data.projects.map(p=>({id:p.id,name:p.name,folders:p.folders.map(f=>({id:f.id,name:f.name}))}))});r.suggestion={projectName:safeName(choice.projectName||'日常资料'),folderName:safeName(choice.folderName||'收集箱')};r.reason=String(choice.reason||'请选择归档位置').slice(0,200);if(choice.projectId&&this.data.projects.some(p=>p.id===choice.projectId&&(!choice.folderId||p.folders.some(f=>f.id===choice.folderId)))){r.phase='等待选择';results.push(await this.resolve({id,projectId:choice.projectId,folderId:choice.folderId}));continue;}}catch(e){r.reason='自动识别暂不可用：'+String(e.message).slice(0,150);r.suggestion={projectName:'日常资料',folderName:'收集箱'};}r.phase='等待选择';this.write();this.onPrompt(r);results.push({id,pending:true});}return results;}
  async resolve({id,projectId,folderId,projectName,folderName,decide,cancel}){return this.locked(async()=>{const r=this.pending.get(id);if(!r)throw new Error('文件已归档或已取消');if(r.phase==='识别中')throw new Error('文件正在识别，请稍候');if(cancel){await fs.promises.unlink(r.staged);this.pending.delete(id);this.write();return true;}if(decide){projectName=r.suggestion?.projectName||'日常资料';folderName=r.suggestion?.folderName||'收集箱';projectId=null;folderId=null;}if(projectName)projectId=this.createNow(null,projectName).id;if(!projectId)throw new Error('请选择项目，或填写新项目名称');if(folderName)folderId=this.createNow(projectId,folderName).id;const dest=this.location(projectId,folderId);let name=r.name,target=path.join(dest,name),n=1;while(fs.existsSync(target)){const ext=path.extname(r.name);name=path.basename(r.name,ext)+' ('+n+++')'+ext;target=path.join(dest,name);}await fs.promises.copyFile(r.staged,target,fs.constants.COPYFILE_EXCL);const record={id,name,size:r.size,projectId,folderId:folderId||null,path:path.relative(this.root,target),createdAt:new Date().toISOString(),excerpt:r.excerpt||'',kind:r.kind||'文件名与类型',summary:r.reason||''};this.data.files.unshift(record);try{this.write();}catch(e){await fs.promises.unlink(target);this.data.files=this.data.files.filter(x=>x.id!==id);throw e;}await fs.promises.unlink(r.staged).catch(()=>{});this.pending.delete(id);this.write();const project=this.data.projects.find(x=>x.id===projectId),folder=project.folders.find(x=>x.id===folderId);this.onSaved(`${name}文件已经存到${project.name}${folder?' / '+folder.name:''}位置啦👌`);return record;});}
  search(query=''){const q=String(query).toLocaleLowerCase().trim().slice(0,300);return this.data.files.map(f=>{const p=this.data.projects.find(p=>p.id===f.projectId),text=[f.name,p?.name,f.summary,f.excerpt].join(' ').toLocaleLowerCase(),at=q?text.indexOf(q):0;if(at<0)return null;const excerpt=f.excerpt||f.summary||'',pos=excerpt.toLocaleLowerCase().indexOf(q);return {id:f.id,name:f.name,project:p?.name||'',folder:p?.folders.find(x=>x.id===f.folderId)?.name||'',kind:f.kind,snippet:excerpt.slice(Math.max(0,pos-35),Math.max(0,pos-35)+130)};}).filter(Boolean).slice(0,60);}
  context(ids){if(!Array.isArray(ids)||ids.length>6)throw new Error('一次最多提及 6 个文件');return ids.map(id=>{const f=this.data.files.find(f=>f.id===id);if(!f)throw new Error('提及的文件已不存在');return {name:f.name,source:f.kind,content:(f.excerpt||'此文件未提取正文，仅提供文件名。').slice(0,6000)};});}
  pathFor(id){const f=this.data.files.find(x=>x.id===id);if(!f)throw new Error('文件不存在');const target=path.resolve(this.root,f.path),rel=path.relative(this.root,target);if(rel.startsWith('..')||path.isAbsolute(rel))throw new Error('无效文件路径');return target;}
}
module.exports={FileLibrary,safeName};
