'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const TEXT=new Set(['.txt','.md','.csv','.json','.log','.js','.ts','.py','.html','.css','.xml','.yaml','.yml','.sql','.lrc','.srt']);
const safeName=s=>{const n=String(s||'').normalize('NFC').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'').trim().slice(0,100);if(!n)throw new Error('请填写项目或文件夹名称');return /^(con|prn|aux|nul|com\d|lpt\d)(\.|$)/i.test(n)?'_'+n:n;};
class FileLibrary{
  constructor({dir,classify,ocr,clipper=require('./web-clip').clipPage,onChange=()=>{},onPrompt=()=>{},onSaved=()=>{}}){Object.assign(this,{classify,ocr,clipper,onChange,onPrompt,onSaved});this.root=path.join(dir,'文件库');this.stage=path.join(this.root,'.待归档');this.file=path.join(this.root,'index.json');fs.mkdirSync(this.stage,{recursive:true});this.data={projects:[],files:[]};try{this.data=JSON.parse(fs.readFileSync(this.file,'utf8'));}catch{}this.pending=new Map();for(const r of this.data.pending||[])if(fs.existsSync(r.staged)){r.phase='等待选择';this.pending.set(r.id,r);}this.queue=Promise.resolve();}
  locked(fn){const p=this.queue.then(fn);this.queue=p.catch(()=>{});return p;}
  write(){fs.writeFileSync(this.file+'.tmp',JSON.stringify({...this.data,pending:[...this.pending.values()]},null,2));fs.renameSync(this.file+'.tmp',this.file);this.onChange();}
  view(){return {projects:this.data.projects,files:this.data.files.map(f=>({...f,path:undefined,excerpt:undefined})),pending:this.pendingGroups(),root:this.root};}
  location(project,folder){const p=this.data.projects.find(x=>x.id===project);if(!p)throw new Error('项目不存在');let result=path.join(this.root,p.directory);if(folder){const f=p.folders.find(x=>x.id===folder);if(!f)throw new Error('文件夹不存在');result=path.join(result,f.directory);}const relative=path.relative(this.root,result);if(relative.startsWith('..')||path.isAbsolute(relative))throw new Error('无效归档路径');return result;}
  async create({projectId,name}){return this.locked(()=>this.createNow(projectId,name));}
  createNow(projectId,name){const clean=safeName(name),id=crypto.randomUUID();let record;if(projectId){const p=this.data.projects.find(x=>x.id===projectId);if(!p)throw new Error('项目不存在');record=p.folders.find(x=>x.name===clean);if(record)return record;record={id,name:clean,directory:clean+'-'+id.slice(0,8)};p.folders.push(record);fs.mkdirSync(this.location(p.id,id),{recursive:true});}else{record=this.data.projects.find(x=>x.name===clean);if(record)return record;record={id,name:clean,directory:clean+'-'+id.slice(0,8),folders:[]};this.data.projects.push(record);fs.mkdirSync(this.location(id),{recursive:true});}this.write();return record;}
  async importDrop(data){
    if(!data||!Array.isArray(data.paths)||!Array.isArray(data.urls))throw Error('无法识别拖入内容');
    if(data.paths.length+data.urls.length>30)throw Error('一次最多拖入 30 个文件或链接');
    const paths=[...new Set(data.paths.filter(x=>typeof x==='string'&&x))],urls=new Set(data.urls),temporary=[];
    for(let i=paths.length-1;i>=0;i--)if(/\.url$/i.test(paths[i])){const bytes=await fs.promises.readFile(paths[i]);const raw=bytes[0]===255&&bytes[1]===254?bytes.subarray(2).toString('utf16le'):bytes.toString('utf8');const url=raw.match(/^URL=(https?:\/\/[^\r\n]+)/im)?.[1];if(url){urls.add(url);paths.splice(i,1);}}
    try{for(const value of urls){const clip=await this.clipper(value);const name=safeName(clip.title)+'.html',dir=path.join(this.stage,'clip-'+crypto.randomUUID());await fs.promises.mkdir(dir);temporary.push(dir);const file=path.join(dir,name);await fs.promises.writeFile(file,clip.html);paths.push(file);}if(!paths.length)throw Error('未识别到文件或网址');return await this.import(paths);}finally{for(const dir of temporary)await fs.promises.rm(dir,{recursive:true,force:true});}
  }
  async extract(file){const ext=path.extname(file).toLowerCase(),stat=await fs.promises.stat(file);if(ext==='.html'&&stat.size<=3*1024*1024){const {JSDOM}=require('jsdom'),dom=new JSDOM(await fs.promises.readFile(file,'utf8'));try{const doc=dom.window.document,sourceUrl=doc.querySelector('meta[name=feimo-source]')?.content;if(sourceUrl){return {text:(doc.querySelector('article')?.textContent||'').slice(0,60000),kind:'网页剪藏',sourceUrl,clipStatus:doc.querySelector('meta[name=feimo-clip-status]')?.content||'saved',clipError:doc.querySelector('meta[name=feimo-clip-error]')?.content||''};}}finally{dom.window.close();}}if(TEXT.has(ext)&&stat.size<=10*1024*1024){const h=await fs.promises.open(file,'r');try{const b=Buffer.alloc(Math.min(stat.size,64000));await h.read(b,0,b.length,0);return {text:b.toString('utf8').slice(0,12000),kind:'文字内容'};}finally{await h.close();}}
    if(ext==='.pdf'&&stat.size<=30*1024*1024){const {PDFParse}=require('pdf-parse'),parser=new PDFParse({data:await fs.promises.readFile(file)});try{return {text:(await parser.getText({first:4})).text.slice(0,12000),kind:'PDF 前四页'};}finally{await parser.destroy();}}
    if(ext==='.docx'&&stat.size<=20*1024*1024)return {text:(await require('mammoth').extractRawText({path:file})).value.slice(0,12000),kind:'文档正文'};
    if(['.png','.jpg','.jpeg','.webp','.bmp','.tiff'].includes(ext)&&stat.size<=30*1024*1024){const d=await this.ocr(file);return {text:d.lines.map(x=>x.text).join('\n').slice(0,12000),kind:'本机图片识别'};}
    return {text:'',kind:'文件名与类型（此格式未读取正文）'};
  }
  pendingGroups(){const result=[],seen=new Set();for(const r of this.pending.values()){if(r.batchId){if(seen.has(r.batchId))continue;seen.add(r.batchId);const rows=[...this.pending.values()].filter(x=>x.batchId===r.batchId);const {staged,excerpt,...visible}=r;result.push({...visible,id:r.batchId,name:rows.length+' 个文件',count:rows.length,files:rows.map(x=>({name:x.name,size:x.size,kind:x.kind})),phase:rows.some(x=>x.phase==='识别中')?'识别中':'等待选择'});}else{const {staged,excerpt,...visible}=r;result.push(visible);}}return result;}
  async import(paths){if(!Array.isArray(paths)||!paths.length||paths.length>30)throw new Error('一次最多拖入 30 个文件');return paths.length===1?this.importOne(paths):this.importBatch(paths);}
  async importBatch(paths){
    const sources=await Promise.all(paths.map(async source=>{const file=path.resolve(String(source)),stat=await fs.promises.stat(file);if(!stat.isFile())throw new Error('请拖入文件，文件夹请在文件库创建');if(stat.size>1024*1024*1024)throw new Error('单个文件最多支持 1 GB');return {file,stat};}));
    const batchId=crypto.randomUUID(),rows=[];
    try{for(const {file,stat} of sources){const id=crypto.randomUUID(),name=safeName(path.basename(file)),staged=path.join(this.stage,id+path.extname(name));await fs.promises.copyFile(file,staged,fs.constants.COPYFILE_EXCL);rows.push({id,batchId,name,size:stat.size,staged,phase:'识别中',suggestion:null});}}
    catch(e){for(const r of rows)await fs.promises.unlink(r.staged).catch(()=>{});throw e;}
    for(const r of rows)this.pending.set(r.id,r);this.write();
    let budget=12000;const contents=[];for(const r of rows){try{const x=await this.extract(r.staged);r.kind=x.kind;r.excerpt=x.text;r.sourceUrl=x.sourceUrl;r.clipStatus=x.clipStatus;r.clipError=x.clipError;}catch{r.kind='文件名与类型';r.excerpt='';}const content=r.excerpt.slice(0,budget);budget-=content.length;contents.push({name:r.name,size:r.size,content});}
    let suggestion={projectName:'日常资料',folderName:'收集箱'},reason='请选择这批文件的统一归档位置';
    try{const choice=await this.classify({name:rows.length+' 个文件',files:contents,projects:this.data.projects.map(p=>({id:p.id,name:p.name,folders:p.folders.map(f=>({id:f.id,name:f.name}))}))});const p=this.data.projects.find(p=>p.id===choice.projectId),folder=p?.folders.find(f=>f.id===choice.folderId);suggestion={projectId:p?.id,folderId:folder?.id,projectName:safeName(choice.projectName||p?.name||'日常资料'),folderName:safeName(choice.folderName||folder?.name||'收集箱')};reason=String(choice.reason||reason).slice(0,200);}catch(e){reason='自动识别暂不可用：'+String(e.message).slice(0,150);}
    for(const r of rows)Object.assign(r,{suggestion,reason,phase:'等待选择'});this.write();this.onPrompt(this.pendingGroups().find(r=>r.id===batchId));return [{id:batchId,pending:true,count:rows.length}];
  }
  async resolve(options){return this.locked(async()=>{const rows=[...this.pending.values()].filter(r=>r.batchId===options.id);return rows.length?this.resolveBatchNow(options,rows):this.resolveOneNow(options);});}
  async resolveBatchNow(options,rows){
    if(rows.some(r=>r.phase==='识别中'))throw new Error('文件正在识别，请稍候');
    if(options.cancel){for(const r of rows)await this.resolveOneNow({id:r.id,cancel:true});return true;}
    let {projectId,folderId,projectName,folderName}=options;
    if(options.decide){const s=rows[0].suggestion||{};projectId=s.projectId;folderId=s.folderId;projectName=projectId?null:s.projectName||'日常资料';folderName=folderId||projectId?null:s.folderName||'收集箱';}
    if(projectName){projectId=this.createNow(null,projectName).id;folderId=null;}if(!projectId)throw new Error('请选择项目，或填写新项目名称');if(folderName)folderId=this.createNow(projectId,folderName).id;this.location(projectId,folderId);
    const results=[];for(const r of rows)results.push(await this.resolveOneNow({id:r.id,projectId,folderId,quiet:true}));
    const p=this.data.projects.find(p=>p.id===projectId),f=p.folders.find(f=>f.id===folderId);this.onSaved(results.length+' 个文件已经存到'+p.name+(f?' / '+f.name:'')+'位置啦👌');return results;
  }
  async importOne(paths){if(!Array.isArray(paths)||!paths.length||paths.length>30)throw new Error('一次最多拖入 30 个文件');const results=[];for(const source of paths){const file=path.resolve(String(source)),stat=await fs.promises.stat(file);if(!stat.isFile())throw new Error('请拖入文件，文件夹请在文件库创建');if(stat.size>1024*1024*1024)throw new Error('单个文件最多支持 1 GB');const id=crypto.randomUUID(),name=safeName(path.basename(file)),staged=path.join(this.stage,id+path.extname(name));await fs.promises.copyFile(file,staged,fs.constants.COPYFILE_EXCL);const r={id,name,size:stat.size,staged,phase:'识别中',suggestion:null};this.pending.set(id,r);this.write();try{const extracted=await this.extract(staged);r.kind=extracted.kind;r.excerpt=extracted.text;r.sourceUrl=extracted.sourceUrl;r.clipStatus=extracted.clipStatus;r.clipError=extracted.clipError;const choice=await this.classify({name,size:r.size,content:extracted.text,projects:this.data.projects.map(p=>({id:p.id,name:p.name,folders:p.folders.map(f=>({id:f.id,name:f.name}))}))});r.suggestion={projectName:safeName(choice.projectName||'日常资料'),folderName:safeName(choice.folderName||'收集箱')};r.reason=String(choice.reason||'请选择归档位置').slice(0,200);if(choice.projectId&&this.data.projects.some(p=>p.id===choice.projectId&&(!choice.folderId||p.folders.some(f=>f.id===choice.folderId)))){r.phase='等待选择';results.push(await this.resolve({id,projectId:choice.projectId,folderId:choice.folderId}));continue;}}catch(e){r.reason='自动识别暂不可用：'+String(e.message).slice(0,150);r.suggestion={projectName:'日常资料',folderName:'收集箱'};}r.phase='等待选择';this.write();this.onPrompt(r);results.push({id,pending:true});}return results;}
  async resolveOneNow({id,projectId,folderId,projectName,folderName,decide,cancel,quiet}){const r=this.pending.get(id);if(!r)throw new Error('文件已归档或已取消');if(r.phase==='识别中')throw new Error('文件正在识别，请稍候');if(cancel){await fs.promises.unlink(r.staged);this.pending.delete(id);this.write();return true;}if(decide){projectName=r.suggestion?.projectName||'日常资料';folderName=r.suggestion?.folderName||'收集箱';projectId=null;folderId=null;}if(projectName)projectId=this.createNow(null,projectName).id;if(!projectId)throw new Error('请选择项目，或填写新项目名称');if(folderName)folderId=this.createNow(projectId,folderName).id;const dest=this.location(projectId,folderId);let name=r.name,target=path.join(dest,name),n=1;while(fs.existsSync(target)){const ext=path.extname(r.name);name=path.basename(r.name,ext)+' ('+n+++')'+ext;target=path.join(dest,name);}await fs.promises.copyFile(r.staged,target,fs.constants.COPYFILE_EXCL);const record={id,name,size:r.size,projectId,folderId:folderId||null,path:path.relative(this.root,target),createdAt:new Date().toISOString(),excerpt:r.excerpt||'',kind:r.kind||'文件名与类型',summary:r.reason||'',sourceUrl:r.sourceUrl,clipStatus:r.clipStatus,clipError:r.clipError};this.data.files.unshift(record);this.pending.delete(id);try{this.write();}catch(e){await fs.promises.unlink(target);this.data.files=this.data.files.filter(x=>x.id!==id);this.pending.set(id,r);throw e;}await fs.promises.unlink(r.staged).catch(()=>{});const project=this.data.projects.find(x=>x.id===projectId),folder=project.folders.find(x=>x.id===folderId);if(!quiet)this.onSaved(`${name}文件已经存到${project.name}${folder?' / '+folder.name:''}位置啦👌`);return record;}
  search(query=''){const q=String(query).toLocaleLowerCase().trim().slice(0,300);return this.data.files.map(f=>{const p=this.data.projects.find(p=>p.id===f.projectId),text=[f.name,p?.name,f.summary,f.excerpt,f.sourceUrl].join(' ').toLocaleLowerCase(),at=q?text.indexOf(q):0;if(at<0)return null;const excerpt=f.excerpt||f.summary||'',pos=excerpt.toLocaleLowerCase().indexOf(q);return {id:f.id,name:f.name,project:p?.name||'',folder:p?.folders.find(x=>x.id===f.folderId)?.name||'',kind:f.kind,snippet:excerpt.slice(Math.max(0,pos-35),Math.max(0,pos-35)+130)};}).filter(Boolean).slice(0,60);}
  context(ids){if(!Array.isArray(ids)||ids.length>6)throw new Error('一次最多提及 6 个文件');return ids.map(id=>{const f=this.data.files.find(f=>f.id===id);if(!f)throw new Error('提及的文件已不存在');return {name:f.name,source:f.sourceUrl||f.kind,content:(f.excerpt||'此文件未提取正文，仅提供文件名。').slice(0,6000)};});}
  pathsFor(ids){if(!Array.isArray(ids)||!ids.length||ids.length>100||ids.some(id=>typeof id!=='string'))throw new Error('一次最多拖出 100 个文件');return [...new Set(ids)].map(id=>{const file=this.pathFor(id);if(!fs.statSync(file).isFile())throw new Error('文件已不存在');return file;});}
  pathFor(id){const f=this.data.files.find(x=>x.id===id);if(!f)throw new Error('文件不存在');const target=path.resolve(this.root,f.path),rel=path.relative(this.root,target);if(rel.startsWith('..')||path.isAbsolute(rel))throw new Error('无效文件路径');return target;}
}
module.exports={FileLibrary,safeName};
