'use strict';
const dns=require('node:dns').promises,net=require('node:net');
const {JSDOM}=require('jsdom'),{Readability}=require('@mozilla/readability');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalizeUrl(value){const u=new URL(String(value).trim());if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('请使用不含登录凭据的 http / https 网址');u.hash='';return u.href;}
function privateAddress(ip){if(net.isIP(ip)===4){const [a,b]=ip.split('.').map(Number);return a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127;}const s=ip.toLowerCase();if(s.startsWith('::ffff:'))return privateAddress(s.slice(7));return s==='::'||s==='::1'||s.startsWith('fc')||s.startsWith('fd')||/^fe[89ab]/.test(s);}
async function publicUrl(url,lookup=dns.lookup){const u=new URL(normalizeUrl(url)),host=u.hostname.replace(/^\[|\]$/g,'');const addresses=net.isIP(host)?[{address:host}]:await lookup(host,{all:true});if(!addresses.length||addresses.some(x=>privateAddress(x.address)))throw Error('网页剪藏仅支持公开网站');return u.href;}
function parsePage(html,url){const dom=new JSDOM(html,{url});try{const doc=dom.window.document;doc.querySelectorAll('script,style,iframe,form,nav,footer,noscript').forEach(n=>n.remove());const title=doc.title||new URL(url).hostname;const article=new Readability(doc.cloneNode(true),{maxElemsToParse:50000}).parse();const node=doc.querySelector('article,main')||doc.body;const text=(article?.textContent||node?.textContent||'').replace(/[ \t]+/g,' ').replace(/\n\s*\n\s*\n/g,'\n\n').trim().slice(0,60000);if(text.length<40)throw Error('网页正文不足，可能需要登录或由脚本加载');return {title:(article?.title||title).trim().slice(0,180),text};}finally{dom.window.close();}}
async function clipPage(value,{fetcher=fetch,lookup=dns.lookup}={}){const sourceUrl=normalizeUrl(value);let url=sourceUrl,title=new URL(url).hostname,text='',clipStatus='saved',clipError='';try{const signal=AbortSignal.timeout(16000);for(let i=0;i<6;i++){await publicUrl(url,lookup);const response=await fetcher(url,{redirect:'manual',signal,headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'Feimo-WebClip/1.0'}});if([301,302,303,307,308].includes(response.status)){const next=response.headers.get('location');if(!next)throw Error('网页跳转地址缺失');url=normalizeUrl(new URL(next,url).href);continue;}if(!response.ok)throw Error('网页返回 '+response.status);if(!/text\/html|application\/xhtml/i.test(response.headers.get('content-type')||''))throw Error('此链接不是可剪藏的网页');if(Number(response.headers.get('content-length'))>3*1024*1024)throw Error('网页超过 3 MB');const reader=response.body.getReader();let size=0,chunks=[];try{while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>3*1024*1024)throw Error('网页超过 3 MB');chunks.push(r.value);}}finally{await reader.cancel().catch(()=>{});}const raw=Buffer.concat(chunks),peek=raw.subarray(0,4096).toString('ascii'),charset=(response.headers.get('content-type')?.match(/charset=["']?([^;"' ]+)/i)||peek.match(/charset=["']?([^"' >;]+)/i))?.[1]||'utf-8';let html;try{html=new TextDecoder(charset).decode(raw);}catch{html=raw.toString('utf8');}({title,text}=parsePage(html,url));break;}if(!text)throw Error('网页跳转次数过多');}catch(e){clipStatus='bookmark';clipError=String(e.message||'网页暂时无法读取').slice(0,180);text='仅保存网址，正文未剪藏：'+clipError;}
 const capturedAt=new Date().toISOString();const html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'"><meta name="feimo-source" content="'+escape(sourceUrl)+'"><meta name="feimo-clip-status" content="'+clipStatus+'"><meta name="feimo-clip-error" content="'+escape(clipError)+'"><title>'+escape(title)+'</title><style>body{max-width:760px;margin:48px auto;padding:24px;font:16px/1.8 system-ui;color:#26323d}article{white-space:pre-wrap;overflow-wrap:anywhere}small{color:#63707b}</style></head><body><h1>'+escape(title)+'</h1><p><a href="'+escape(sourceUrl)+'">'+escape(sourceUrl)+'</a></p><small>'+capturedAt+' · '+(clipStatus==='saved'?'网页正文快照':'仅收藏链接 · 正文未剪藏')+'</small><article>'+escape(text)+'</article></body></html>';return {title,text,html,sourceUrl,clipStatus,clipError,capturedAt};}
module.exports={normalizeUrl,privateAddress,publicUrl,parsePage,clipPage};
