'use strict';
(() => {
  const {esc,icon,safe}=window.IslandWidgets;
  async function mount(root){
    const state=await api.islandState();
    root.innerHTML=`<div class="connection-settings"><div class="card"><h3>助手显示方式</h3><p class="hint">在小精灵和屏幕顶部模式之间切换，保留同一套数据与形象。</p><div class="mode-options"><button class="btn" data-mode="pet">${icon('Paw')} 小精灵模式</button><button class="btn" data-mode="island">${icon('Widget')} 顶部模式</button></div><p class="hint">顶部模式点击药丸展开；移开后收起。正在批准、回复或输入时保持展开。</p></div><div class="card"><h3>顶部活动药丸</h3><div class="pill-options"></div></div><div class="card"><h3>会话桥接 · 批准与回复</h3><p class="hint">安装后，新会话可以直接批准、拒绝、回答问题和定位终端。仅观察旧日志的会话不会提供虚假的批准按钮。Codex 安装后需在原程序的 Hooks 设置中信任；不同客户端版本对问题回答的支持以客户端为准。</p><div class="actionbar"><button class="btn hook-preview" data-source="claude">配置 Claude Code</button><button class="btn hook-preview" data-source="codex">配置 Codex</button><button class="btn" id="bridge-clear">撤销记住的授权</button></div><div class="hook-status hint"></div></div><div class="card"><h3>音乐药丸</h3><p class="hint">通过 Windows 系统媒体会话读取与控制播放。网易云音乐需启用系统媒体控制；无媒体会话时显示未连接。</p><label class="field">播放器<select id="music-player"><option value="netease">网易云音乐</option><option value="system">系统当前播放器</option></select></label><button class="btn" id="music-open">打开网易云音乐</button></div><div class="integration-settings"></div></div>`;
    root.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('primary',b.dataset.mode===state.mode);b.onclick=()=>safe(async()=>{await api.islandMode(b.dataset.mode);root.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('primary',x===b));UI.toast('显示模式已切换');});});
    const options=root.querySelector('.pill-options');const names=[['agents','Coding 会话'],['music','音乐'],['focus','倒计时'],['chat','问答'],['files','文件库'],...state.integrations.map(x=>[x.id,x.name])];
    for(const [id,name]of names){const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${id}" ${state.pills.includes(id)?'checked':''}/> ${esc(name)}`;options.append(label);label.querySelector('input').onchange=()=>safe(()=>api.islandPills([...options.querySelectorAll('input:checked')].map(i=>i.value)));}
    root.querySelector('.hook-status').textContent=state.bridge.error||`${state.bridge.requests.length} 项待处理请求 · ${state.bridge.rules.length} 项记住的授权`;
    root.querySelector('#bridge-clear').onclick=()=>safe(async()=>{await api.hooksClearRules();UI.toast('已撤销记住的授权');});
    root.querySelectorAll('.hook-preview').forEach(b=>b.onclick=()=>preview(b.dataset.source));
    const player=root.querySelector('#music-player');player.value=(await api.getSettings()).music?.player||'netease';player.onchange=()=>safe(()=>api.musicConfig({player:player.value,enabled:true}));root.querySelector('#music-open').onclick=()=>safe(()=>api.musicOpen());
    const musicPanel=document.createElement('article');musicPanel.className='card';IslandWidgets.musicCard(musicPanel,state.music);root.querySelector('.connection-settings').append(musicPanel);
    const list=root.querySelector('.integration-settings');
    for(const item of state.integrations){const card=document.createElement('article');card.className='card integration-config';card.dataset.service=item.id;
      card.innerHTML=`<h3>${icon(item.icon)} ${esc(item.name)} <span class="badge">${item.configured?'已配置':'未配置'}</span></h3><p class="hint service-status">${esc(item.error||item.data?.summary||'保存配置后会立即测试连接。')}</p><label class="integration-switch"><input type="checkbox" class="service-enabled" ${item.config?.enabled?'checked':''}/> 启用此服务</label>${item.id==='github'?`<div class="field"><label>仓库（可选；留空显示自己的开放 PR）</label><input class="service-repo" placeholder="owner/repository" value="${esc(item.config?.repo||'')}"/></div>`:''}${item.id==='n8n'?`<div class="field"><label>n8n 实例地址</label><input class="service-url" placeholder="https://n8n.example.com" value="${esc(item.config?.baseUrl||'')}"/></div>`:''}<div class="field"><label>${item.id==='github'?'GitHub Token':'API 密钥'} · 本机加密存储</label><input class="service-key" type="password" autocomplete="new-password" placeholder="${item.configured?'留空保留现有密钥':'填写密钥'}"/></div>${item.id==='notion'?'<p class="hint">与 Notion 日程共用本机已保存的 Token；需在 Notion 中将对应页面分享给集成。</p>':''}<div class="actionbar"><button class="btn primary service-save">保存并连接</button>${item.id==='github'?'<button class="btn github-local">连接本机 GitHub 账号</button>':''}<button class="btn service-refresh">刷新</button><button class="btn service-disconnect">断开</button></div>`;
      card.querySelector('.service-save').onclick=()=>safe(async()=>{const b=card.querySelector('.service-save');b.disabled=true;try{const result=await api.integrationsSave({id:item.id,config:{enabled:card.querySelector('.service-enabled').checked,repo:card.querySelector('.service-repo')?.value,baseUrl:card.querySelector('.service-url')?.value},key:card.querySelector('.service-key').value});card.querySelector('.service-key').value='';status(result,item.id,card);UI.toast('配置已保存');}finally{b.disabled=false;}});
      card.querySelector('.service-refresh').onclick=()=>safe(async()=>status(await api.integrationsRefresh(item.id),item.id,card));card.querySelector('.service-disconnect').onclick=()=>safe(async()=>{status(await api.integrationsDisconnect(item.id),item.id,card);card.querySelector('.service-enabled').checked=false;});
      if(item.id==='github')card.querySelector('.github-local').onclick=()=>safe(async()=>{const b=card.querySelector('.github-local');b.disabled=true;try{status(await api.integrationsGithubLocal(),item.id,card);card.querySelector('.service-enabled').checked=true;}finally{b.disabled=false;}});
      const details=document.createElement('details');details.innerHTML='<summary>查看服务卡片</summary><div class="service-preview"></div>';card.append(details);IslandWidgets.serviceCard(details.querySelector('.service-preview'),item);list.append(card);
    }
  }
  function status(state,id,card){const s=state.integrations.find(x=>x.id===id);const preview=card.querySelector('.service-preview');if(preview)IslandWidgets.serviceCard(preview,s);card.querySelector('.service-status').textContent=s.error||s.data?.summary||(s.config?.enabled?'等待连接':'已断开');card.querySelector('.badge').textContent=s.configured?'已配置':'未配置';}
  function preview(source,remove=false){return safe(async()=>{const p=await api.hooksPreview(source,remove),dialog=document.createElement('dialog');dialog.className='bridge-preview';dialog.innerHTML=`<h3>${remove?'移除':'安装'} ${esc(source)} 会话桥接</h3><p class="hint">仅修改斐墨自身的 hooks，保留其他配置，写入前自动备份。</p><details><summary>修改前</summary><pre></pre></details><details open><summary>修改后</summary><pre></pre></details><div class="actionbar"><button class="btn primary hook-confirm">确认${remove?'移除':'安装'}</button><button class="btn hook-remove">预览移除</button><button class="btn hook-close">取消</button></div>`;const pre=dialog.querySelectorAll('pre');pre[0].textContent=p.before;pre[1].textContent=p.after;dialog.querySelector('.hook-confirm').onclick=()=>safe(async()=>{await api.hooksApply({source,remove,fingerprint:p.fingerprint});dialog.close();UI.toast('配置已更新，请重新启动对应会话');});dialog.querySelector('.hook-remove').onclick=()=>{dialog.close();preview(source,true);};dialog.querySelector('.hook-close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();document.body.append(dialog);dialog.showModal();});}
  window.FeimoConnections={mount};
})();
