'use strict';
(()=>{
 const api=window.api,$=s=>document.querySelector(s),{safe,esc,icon}=IslandWidgets;
 const dock=$('#quick-pills'),pill=$('#compact'),title=pill.querySelector('.compact-copy strong'),status=$('#compact-status');let state,hideTimer,cardType='',hover=false;
 const controls=document.createElement('span');controls.className='compact-controls';pill.insertBefore(controls,$('#compact-open'));
 const quick=[['ChatDots','问答','chat'],['CalendarDays','日程','schedule'],['Timer','倒计时','focus'],['Music','白噪音','noise'],['ClipboardText','剪贴板','clipboard'],['NoteText','速记','notes'],['Palette','配色','palette'],['Broom','清洗文字','clean'],['Image','区域截图','screenshot'],['ChartBar','Codex额度','quota'],['Folder','存入文件','files']];
 const row=document.createElement('div');row.className='quick-pill-row';const card=document.createElement('section');card.className='quick-card';card.hidden=true;dock.append(row,card);
 for(const [glyph,name,type]of quick){const b=document.createElement('button');b.className='quick-pill';b.innerHTML=icon(glyph,16)+' '+esc(name);b.onclick=()=>safe(()=>open(type));row.append(b);}
 row.onwheel=e=>{e.preventDefault();row.scrollBy({left:e.deltaY||e.deltaX,behavior:'smooth'});};
 const close=()=>{dock.hidden=true;card.hidden=true;cardType='';window.IslandHit?.();};
 function reveal(){clearTimeout(hideTimer);if(!$('#island').classList.contains('collapsed'))return;dock.hidden=false;void api.islandReveal();}
 function enter(){clearTimeout(hideTimer);hover=true;api.islandHover(true);}
 function leave(e){if(e?.relatedTarget&&(dock.contains(e.relatedTarget)||pill.contains(e.relatedTarget)||document.getElementById('island-cards')?.contains(e.relatedTarget))){enter();return;}clearTimeout(hideTimer);hideTimer=setTimeout(()=>{if(dock.matches(':hover')||pill.matches(':hover')||document.getElementById('island-cards')?.matches(':hover')||dock.contains(document.activeElement))return;hover=false;api.islandHover(false);api.islandLeave();close();},450);}
 window.IslandQuickHover={enter,leave};
 pill.onmouseenter=()=>{enter();reveal();};pill.onmouseleave=leave;dock.onmouseenter=enter;dock.onmouseleave=leave;
 $('#compact-open').onclick=e=>{e.stopPropagation();close();safe(()=>api.islandWorkbar('voice'));};
 setInterval(()=>{if(!dock.hidden&&(hover||dock.contains(document.activeElement)))void api.islandReveal();},1000);
 function head(text){card.hidden=false;card.innerHTML=`<div class="quick-card-heading"><strong>${esc(text)}</strong><button class="icon-btn" aria-label="关闭快捷卡片">${icon('CloseCircle',16)}</button></div><div class="quick-card-body"></div>`;card.querySelector('.quick-card-heading button').onclick=()=>{card.hidden=true;cardType='';};return card.querySelector('.quick-card-body');}
 const action=(root,text,fn,primary=false)=>{const b=document.createElement('button');b.className='btn small'+(primary?' primary':'');b.textContent=text;b.onclick=()=>safe(fn);root.append(b);return b;};
 async function open(type){cardType=type;await api.islandReveal();
  if(type==='screenshot'){close();await api.screenshot();return;}
  if(type==='clean'||type==='ocr'){const r=head(type==='clean'?'正在清洗文字…':'正在提取图片文字…');await api.clipboardRunQuick(type==='clean'?'text':'image');r.textContent='已开始处理，完成后自动复制。';return;}
  if(type==='chat'){const body=head('问斐墨'),form=document.createElement('form'),input=document.createElement('textarea'),send=document.createElement('button');input.placeholder='想问什么？';input.rows=3;input.setAttribute('aria-label','快捷问答问题');send.className='btn primary';send.textContent='发送';send.type='submit';form.append(input,send);body.append(form);form.onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;close();safe(()=>api.islandQuickChat(text));};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();form.requestSubmit();}};input.focus();return;}
    if(type==='files'){await api.fileSelect();return;}
  const root=head(({focus:'专注一会儿',noise:'白噪音',schedule:'新建日程',clipboard:'剪贴板',notes:'记下一个想法',palette:'精选配色',quota:'Codex 额度'})[type]);
  if(type==='focus'){const f=await api.focusState();root.innerHTML=`<label>时长（分钟）<input type="number" min="1" max="720" value="25" aria-label="快捷计时分钟"></label><label>任务<select aria-label="快捷计时任务">${f.labels.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')}</select></label><label>方式<select aria-label="快捷计时方式"><option value="pomodoro">番茄钟</option><option value="countdown">倒计时</option></select></label>`;action(root,'开始计时',async()=>{await api.focusStart({minutes:+root.querySelector('input').value,labelId:root.querySelectorAll('select')[0].value,mode:root.querySelectorAll('select')[1].value});close();},true);}
  if(type==='schedule'){root.innerHTML='<input aria-label="日程标题" placeholder="要做什么？" maxlength="200"><input aria-label="日程时间" type="datetime-local">';action(root,'保存日程',async()=>{const [text,date]=root.querySelectorAll('input');if(!text.value.trim()||!date.value)throw Error('请填写标题和时间');await api.calendarAdd({title:text.value.trim(),startsAtUtc:new Date(date.value).toISOString(),reminderOffsets:[15]});root.textContent='日程已经记好啦。';},true);}
  if(type==='notes'){root.innerHTML='<input aria-label="速记标题" placeholder="标题（可选）" maxlength="80"><textarea aria-label="速记内容" placeholder="记下此刻的想法…" rows="4" maxlength="30000"></textarea>';action(root,'保存速记',async()=>{await api.toolboxSaveNote({title:root.querySelector('input').value,text:root.querySelector('textarea').value});root.textContent='速记已经收好啦。';},true);}
  if(type==='clipboard'){const d=await api.toolboxState();for(const c of d.clips.slice(0,8)){const b=action(root,c.kind==='image'?'复制图片':c.value.slice(0,45),()=>api.toolboxCopyClip(c.id));b.classList.add('quick-clip');if(c.kind==='image'){const img=document.createElement('img');img.src=c.value;img.alt='剪贴板图片';b.prepend(img);}}action(root,'收录当前剪贴板',async()=>{await api.toolboxCapture();await open('clipboard');},true);}
  if(type==='palette'){for(const p of FeimoColors.curated){const line=document.createElement('div');line.className='quick-swatches';line.setAttribute('aria-label',p.name);for(const color of p.colors){const b=document.createElement('button');b.style.background=color;b.title=color;b.setAttribute('aria-label','复制 '+color);b.onclick=()=>safe(()=>api.clipboardWriteText(color));line.append(b);}root.append(line);}}
  if(type==='quota'){const limits=(await api.agentsSnapshot()).limits?.codex;root.textContent=limits?[['短时',limits.primary],['周度',limits.secondary]].filter(([,v])=>v).map(([n,v])=>`${n}剩余 ${Math.max(0,100-v.usedPercent).toFixed(0)}%`).join(' · '):'暂无账户额度，点击刷新获取。';action(root,'刷新额度',async()=>{await api.limitsRefresh();await open('quota');});}
  if(type==='noise'){let n=await api.soundscapeState();const select=document.createElement('select');select.setAttribute('aria-label','白噪音预设');select.innerHTML=(n.catalog.mixes||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');root.append(select);const tracks=document.createElement('div');root.append(tracks);const command=async patch=>{n=await api.soundscapeCommand(patch);paint();};const paint=()=>SoundscapeUI.tracks(tracks,n,patch=>safe(()=>command(patch)),{removable:true});select.onchange=()=>safe(()=>command({preset:select.value}));action(root,n.playing?'暂停':'播放',async()=>{await command({playing:!n.playing});await open('noise');},true);paint();}
 }
 const selection=new CompactState.Selection();let controlKey='';
 const switcher=document.createElement('button');switcher.id='compact-switch';switcher.className='icon-btn';switcher.innerHTML=icon('SortDownUp',16);pill.insertBefore(switcher,$('#compact-open'));
 switcher.onclick=e=>{e.stopPropagation();selection.next();render();};
 function render(){if(!state)return;const rows=CompactState.activities(state),current=selection.update(rows),voice=state.voice||{},f=state.focus?.active,m=state.music||{};let buttons=[];
  pill.dataset.activity=current.id;if(title.textContent!==current.name)title.textContent=current.name;if(status.textContent!==current.line)status.textContent=current.line;status.title=current.line;
  switcher.hidden=rows.length<2;switcher.setAttribute('aria-label','切换状态显示');switcher.title=rows.length>1?`切换状态（${rows.findIndex(r=>r.id===current.id)+1}/${rows.length}）：${rows.map(r=>r.name).join('、')}`:'';
  $('#compact-music').hidden=current.id!=='music';
  const toggle=$('#compact-music [data-music="toggle"]');const musicKey=String(!!m.playing);if(toggle.dataset.state!==musicKey){toggle.dataset.state=musicKey;toggle.innerHTML=icon(m.playing?'Pause':'Play',16);toggle.setAttribute('aria-label',m.playing?'暂停音乐':'继续音乐');}
  for(const [command,can]of [['toggle','canToggle'],['previous','canPrevious'],['next','canNext']])$('#compact-music [data-music="'+command+'"]').disabled=!m[can];
  if(current.id==='voice'&&['listening','paused'].includes(voice.phase))buttons=[['Pause',voice.phase==='paused'?'继续听写':'暂停听写',()=>api.voicePause()],['Stop','结束听写',()=>api.voiceFinish()]];
  else if(current.id==='attention')buttons=[['ChatDots','查看待处理事项',()=>api.islandWorkbar('agents')]];
  else if(current.id==='focus')buttons=[[f.status==='paused'?'Play':'Pause',f.status==='paused'?'继续计时':'暂停计时',()=>f.status==='paused'?api.focusResume():api.focusPause()],['Stop','结束计时',()=>api.focusStop()]];
  else if(current.id==='noise')buttons=[['Pause','暂停白噪音',()=>api.soundscapeCommand({playing:false})]];
  const key=current.id+':'+buttons.map(b=>b[1]).join('|');if(key!==controlKey){controlKey=key;controls.replaceChildren();if(current.id==='voice'&&voice.phase==='listening'){const wave=document.createElement('span');wave.className='compact-wave';for(let i=0;i<4;i++)wave.append(document.createElement('i'));controls.append(wave);}for(const [glyph,label,fn]of buttons){const b=document.createElement('button');b.className='icon-btn';b.innerHTML=icon(glyph,16);b.setAttribute('aria-label',label);b.onclick=e=>{e.stopPropagation();safe(fn);};controls.append(b);}}
  controls.querySelectorAll('.compact-wave i').forEach((bar,i)=>bar.style.height=(4+(voice.level||0)*14+Math.abs(Math.sin((voice.elapsed||0)+i))*8)+'px');
 }
 const hide=document.createElement('button');hide.id='compact-hide';hide.className='capsule-hide';hide.setAttribute('aria-label','收起胶囊');hide.title='收起胶囊 · 也可向上拖动';hide.textContent='⌃';document.body.append(hide);hide.onclick=e=>{e.stopPropagation();close();safe(()=>api.islandHide());};let swipe=null;pill.addEventListener('pointerdown',e=>{if(e.target.closest('button,input'))return;swipe={id:e.pointerId,y:e.clientY};pill.setPointerCapture(e.pointerId);});pill.addEventListener('pointerup',e=>{if(swipe&&swipe.id===e.pointerId&&swipe.y-e.clientY>20){close();safe(()=>api.islandHide());}swipe=null;});pill.addEventListener('pointercancel',()=>{swipe=null;});pill.addEventListener('wheel',e=>{if(e.deltaY< -12&&!e.target.closest('input')){e.preventDefault();close();safe(()=>api.islandHide());}},{passive:false});
 api.onIslandChanged(s=>{state=s;render();});api.onVoiceChanged(v=>{if(state){state.voice=v;render();}});api.onFocusTick(f=>{if(state){state.focus.active=f;render();}});api.onSoundscapeChanged(n=>{if(state){state.noise=n;render();}});api.onAgentsSnapshot(a=>{if(state){state.agents=a;render();}});api.onIslandExpanded(on=>{if(on)close();});api.islandState().then(s=>{state=s;render();});
 new ResizeObserver(()=>window.IslandHit?.()).observe(dock);
})();
