'use strict';
(() => {
  const {esc,icon,safe,requestCard,sessionCard,serviceCard,musicCard}=IslandWidgets,$=s=>document.querySelector(s);
  let state=null,selected='workbench',workbenchTab='voice',expandedKnown=false,expanded=false,collapseTimer=null,signature='',requestIndex=0,petId='',pets=[],busy=false,embeddedFocused=false,reply='',assistant=null,attachment=null,frame=null;
  function expand(on){expandedKnown=true;expanded=!!on;$('#island').classList.toggle('collapsed',!expanded);if(on){$('#quick-pills').hidden=true;renderPanel();}publishHit();}
  $('#compact').onkeydown=null;$('#compact').onclick=null;$('#collapse').onclick=()=>safe(()=>api.islandExpand(false));
  $('#compact').onmouseenter=()=>clearTimeout(collapseTimer);
  $('#island').onmouseenter=()=>clearTimeout(collapseTimer);
  $('#island').onmouseleave=()=>{clearTimeout(collapseTimer);collapseTimer=setTimeout(()=>{if(busy||embeddedFocused||state?.bridge.requests.length||document.querySelector('input:focus,textarea:focus,select:focus')||document.querySelector('dialog[open]'))return;safe(()=>api.islandExpand(false));},650);};
  $('#settings').onclick=()=>safe(()=>api.islandWorkbar('connections'));$('#workbench').onclick=()=>safe(()=>api.islandWorkbar('voice'));$('#chat-workbench').onclick=()=>safe(()=>api.islandWorkbar('chat'));
  $('#content').onscroll=()=>$('#content').classList.toggle('is-scrolled',$('#content').scrollTop>2);
  function update(s){
    state=s;$('#island').classList.toggle('idle-dot',!!s.idle);expand(s.expanded);$('#compact-music').hidden=!s.music.playing;const attention=s.bridge.requests.length;const live=s.agents.sessions.filter(x=>x.status==='running');
    $('#compact-status').textContent=attention?`${attention} 项等待你的回复`:s.music.playing?s.music.title||'音乐播放中':live.length?`${live.length} 个 Agent 正在工作`:'你的顶部工作台';
    $('#compact-count').hidden=!attention;$('#compact-count').textContent=String(attention);
    $('#island-status').textContent=attention?'有任务需要你的决定。':live.length?`${live.length} 个 Agent 会话进行中`:'专注眼前，让事情顺畅推进。';
    const q=s.agents.limits?.codex;$('#quota').hidden=!q;$('#quota').textContent=q?`Codex · ${q.primary?`短时剩余 ${Math.max(0,100-q.primary.usedPercent).toFixed(0)}%`:''} ${q.secondary?`· 周剩余 ${Math.max(0,100-q.secondary.usedPercent).toFixed(0)}%`:''}`:'';
    if(petId!==s.pet.style&&pets.length){petId=s.pet.style;const pet=pets.find(x=>x.id===petId)||pets[0];for(const target of document.querySelectorAll('.brand-avatar,.compact-avatar')){target.replaceChildren();if(pet.type==='orb'){const f=document.createElement('iframe');f.src='../../'+pet.orb;f.onload=()=>sendScene();f.title=pet.name;f.tabIndex=-1;target.append(f);}else target.append(PetAvatar.eous(target.classList.contains('brand-avatar')?52:36));}}
    sendScene();
    const catalog=[{id:'workbench',name:'工作台',icon:'Widget'},{id:'agents',name:'Agents',icon:'CodeSquare',count:attention},{id:'focus',name:'倒计时',icon:'Timer'},{id:'files',name:'文件库',icon:'Folder'},{id:'music',name:'Music',icon:'Music'},...s.integrations];
    const visible=catalog.filter(x=>x.id==='workbench'||s.pills.includes(x.id)||(x.id==='agents'&&attention));if(!visible.length)visible.push(catalog[0]);if(!visible.some(x=>x.id===selected))selected=visible[0].id;
    const nav=$('#pills'),scroll=nav.scrollLeft;nav.innerHTML=visible.map(x=>`<button data-pill="${x.id}" class="${selected===x.id?'active':''}" aria-pressed="${selected===x.id}" title="${esc(x.name)}">${icon(x.icon,16)} ${esc(x.name)}${x.count?`<span class="count">${x.count}</span>`:''}${x.config?.enabled?`<span class="pill-dot" style="--service-color:${x.color}"></span>`:''}</button>`).join('');nav.scrollLeft=scroll;
    nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.pill;signature='';nav.querySelectorAll('button').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderPanel();});
    renderPanel();
  }
  function sendScene(){if(!state)return;const scene=state.music.playing&&state.petState.state==='idle'?'soundscapePlaying':state.petState.scene||state.petState.state;document.querySelectorAll('.brand-avatar iframe,.compact-avatar iframe').forEach(f=>f.contentWindow?.postMessage({type:'feimo:orb-state',state:scene},'*'));}
  api.onPetState(pet=>{if(state){state.petState=pet;sendScene();}});
  $('.brand-avatar').onclick=()=>document.querySelectorAll('.brand-avatar iframe').forEach(f=>f.contentWindow?.postMessage({type:'feimo:orb-event',scene:'interaction'},'*'));
  function renderPanel(){
    if(!state||!expanded)return;const embedded=['workbench','agents','focus','files'].includes(selected);$('#full-workbench').hidden=!embedded;$('#content').classList.toggle('full-workbench-mode',embedded);if(embedded){$('#live-panel').hidden=true;$('#chat-panel').hidden=true;const f=$('#full-workbench'),tab=selected==='workbench'?workbenchTab:selected,primary=selected!=='workbench',key=tab+':'+primary;if(f.dataset.route!==key){f.dataset.route=key;f.contentWindow?.postMessage({type:'feimo:workbench-navigate',tab,primary},'*');}return;}$('#chat-panel').hidden=selected!=='chat';$('#live-panel').hidden=selected==='chat';if(selected==='chat')return;
    const panel=$('#live-panel');let data;
    if(selected==='agents')data={files:state.files.pending,bridge:state.bridge,agents:state.agents.sessions,notices:state.notices};else if(selected==='files')data=state.files;else if(selected==='music')data=state.music;else if(selected==='focus')data=state.focus;else data=state.integrations.find(x=>x.id===selected);
    const next=selected+JSON.stringify(data);if(next===signature)return;
    // Live progress must not replace a question field the user is currently typing in.
    const active=document.activeElement;if(panel.contains(active)&&active?.matches('input,textarea,select')&&((selected==='agents'&&state.bridge.requests.some(r=>panel.dataset.request===r.id))||selected==='files'))return;
    signature=next;panel.replaceChildren();panel.dataset.request='';
    if(selected==='agents'){
      for(const r of state.files.pending)if(r.phase==='等待选择'){const box=document.createElement('article');box.className='card';FileLibraryUI.choose(box,r,state.files,api);panel.append(box);}
      for(const n of state.notices||[]){const card=document.createElement('article');card.className='session-tile notice-tile';const copy=document.createElement('p');copy.className='session-summary';copy.textContent=n.text;const close=document.createElement('button');close.className='icon-btn';close.setAttribute('aria-label','关闭提示');close.innerHTML=icon('CloseCircle',16);close.onclick=()=>safe(()=>api.islandDismissNotice(n.id));card.append(copy,close);panel.append(card);}
      if(state.bridge.requests.length){requestIndex=Math.min(requestIndex,state.bridge.requests.length-1);const picker=document.createElement('div');picker.className='request-picker';picker.innerHTML=`<button class="btn small" id="request-prev">上一项</button><span>${requestIndex+1} / ${state.bridge.requests.length}</span><button class="btn small" id="request-next">下一项</button>`;panel.append(picker);for(const [id,step]of [['request-prev',-1],['request-next',1]])picker.querySelector('#'+id).onclick=()=>{requestIndex=(requestIndex+step+state.bridge.requests.length)%state.bridge.requests.length;signature='';renderPanel();};const box=document.createElement('div'),r=state.bridge.requests[requestIndex];panel.dataset.request=r.id;requestCard(box,r);panel.append(box);}
      const sessions=state.agents.sessions;if(!sessions.length&&!state.bridge.requests.length&&!state.notices?.length){panel.innerHTML='<div class="empty">暂无活动会话。<br/>启动 Coding Agent，或在连接设置中安装会话桥接。</div>';}
      for(const s of sessions)panel.append(sessionCard(s,state.bridge));
    }else if(selected==='files'){panel.className='';FileLibraryUI.mount(panel,state.files,api);}
    else if(selected==='music'){panel.className='card';musicCard(panel,state.music);}
    else if(selected==='focus'){
      panel.className='';const a=state.focus.active;panel.innerHTML=a?`<div class="card"><div class="eyebrow">${a.mode==='pomodoro'?'POMODORO':'FOCUS'}</div><h3>${esc(state.focus.labels.find(l=>l.id===a.labelId)?.name||'专注一会儿')}</h3><div class="focus-clock">${format(a.remainingMs/1000)}</div><div class="actionbar"><button class="btn primary" id="focus-toggle">${a.status==='paused'?'继续':'暂停'}</button><button class="btn" id="focus-stop">结束计时</button><button class="btn" id="focus-records">统计与记录</button></div></div>`:'<div class="empty">今天先专注一件事。<div class="actionbar"><button class="btn primary" id="focus-create">开始计时</button><button class="btn" id="focus-noise">白噪音</button></div></div>';
      if(a){$('#focus-toggle').onclick=()=>safe(()=>a.status==='paused'?api.focusResume():api.focusPause());$('#focus-stop').onclick=()=>safe(()=>api.focusStop());$('#focus-records').onclick=()=>safe(()=>api.islandWorkbar('focus'));}else{$('#focus-create').onclick=()=>safe(()=>api.islandWorkbar('focus'));$('#focus-noise').onclick=()=>safe(()=>api.islandWorkbar('focus:soundscape'));}
    }else{panel.className='card';if(data)serviceCard(panel,data);}
    if(selected==='agents')panel.className='';
  }
  const format=secs=>{const s=Math.max(0,Math.ceil(secs));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;};
  const message=(text,user=false)=>{const el=document.createElement('article');el.className='chat-message'+(user?' user':'');if(user)el.textContent=text;else el.append(UI.renderMarkdown(text));$('#chat-messages').append(el);return el;};
  $('#chat-form').onsubmit=event=>{event.preventDefault();if(busy)return;safe(async()=>{const input=$('#chat-input'),text=input.value.trim();if(!text)return;const prompt=attachment?`${text}\n\n附件 ${attachment.name}：\n${attachment.text}`:text;input.value='';message(text,true);assistant=message('让我想想喔…');reply='';busy=true;$('#send').hidden=true;$('#stop').hidden=false;try{const result=await api.chatSend(prompt,window.FileMentions?.ids(text)||[]);if(result.reply){reply=result.reply;assistant.replaceChildren(UI.renderMarkdown(reply));}else if(result.aborted)assistant.replaceChildren(UI.renderMarkdown(reply+'\n\n（已停止）'));}catch(e){assistant.replaceChildren(UI.renderMarkdown('回答失败：'+e.message));throw e;}finally{busy=false;$('#send').hidden=false;$('#stop').hidden=true;attachment=null;$('#attachment').hidden=true;}});};
  $('#chat-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#chat-form').requestSubmit();}};
  api.onChatDelta(text=>{if(!busy||!assistant)return;reply=text.full??(reply+(text.delta||''));if(frame)return;frame=requestAnimationFrame(()=>{frame=null;assistant.replaceChildren(UI.renderMarkdown(reply));});});
  $('#stop').onclick=()=>safe(()=>api.chatStop());$('#new-chat').onclick=()=>safe(async()=>{if(busy)await api.chatStop();await api.chatClear();$('#chat-messages').replaceChildren();});
  $('#file').onclick=()=>safe(async()=>{const file=await api.islandDropFile();if(file){attachment=file;$('#attachment').textContent='已附加 '+file.name;$('#attachment').hidden=false;}});
  const resize=()=>{if(!expanded)return;if(selected==='workbench'){void api.islandResize(620);return;}const panel=selected==='chat'?$('#chat-panel'):$('#live-panel');const desired=$('header').offsetHeight+panel.scrollHeight+$('footer').offsetHeight+44;void api.islandResize(Math.min(640,Math.max(280,desired))).catch(()=>{});};
  const observer=new ResizeObserver(resize);for(const el of [$('#live-panel'),$('#chat-messages'),$('header')])observer.observe(el);
  document.addEventListener('dragover',event=>{event.preventDefault();void api.islandExpand(true);});document.addEventListener('drop',event=>{event.preventDefault();const files=[...event.dataTransfer.files].map(f=>api.filePath(f));if(files.length){selected='files';signature='';renderPanel();safe(()=>api.fileImport(files));}});
  document.querySelectorAll('[data-music]').forEach(b=>b.onclick=e=>{e.stopPropagation();safe(()=>api.musicCommand(b.dataset.music));});
  const lyricTick=()=>{if(!state?.music.playing)return;const m=state.music,secs=m.position+(Date.now()-(m.sampledAt||Date.now()))/1000;let text=m.title||'音乐播放中';for(const l of m.lyrics||[])if(l.time<=secs)text=l.text;const root=$('#compact-lyric');if(root.dataset.text!==text){root.dataset.text=text;const span=document.createElement('span');span.textContent=text;root.replaceChildren(span);requestAnimationFrame(()=>{const overflow=span.scrollWidth-root.clientWidth;if(overflow>0&&!matchMedia('(prefers-reduced-motion: reduce)').matches)span.animate([{transform:'translateX(0)',offset:0},{transform:'translateX(0)',offset:.12},{transform:'translateX(-'+(overflow+6)+'px)',offset:.8},{transform:'translateX(-'+(overflow+6)+'px)',offset:1}],{duration:Math.max(6000,overflow*70),iterations:Infinity,direction:'alternate',easing:'linear'});});}};setInterval(lyricTick,300);
  window.addEventListener('message',e=>{if(e.source===$('#full-workbench').contentWindow&&e.data?.type==='feimo:workbench-busy')embeddedFocused=!!e.data.busy;});
  function navigate(tab){const route=String(tab).split(':')[0];selected=['agents','focus','files'].includes(route)?route:'workbench';workbenchTab=tab;signature='';$('#full-workbench').dataset.route='';renderPanel();}
  $('#full-workbench').onload=()=>navigate(state?.module||'voice');api.onIslandNavigate(navigate);window.FeimoNavigate=navigate;api.onIslandIdle(idle=>$('#island').classList.toggle('idle-dot',idle));
  function publishHit(){const rects=[...document.querySelectorAll('#island,#quick-pills:not([hidden]),dialog[open]')].map(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};});api.islandHit?.(rects);}
  const hitObserver=new ResizeObserver(publishHit);hitObserver.observe($('#island'));document.addEventListener('animationstart',()=>{let end=performance.now()+450;const tick=()=>{publishHit();if(performance.now()<end)requestAnimationFrame(tick);};requestAnimationFrame(tick);});
  api.onIslandChanged(update);api.onIslandExpanded(expand);api.onFocusTick(()=>safe(async()=>update(await api.islandState())));
  (async()=>{pets=await api.getPets();update(await api.islandState());const history=await api.chatHistory();for(const m of history||[])message(m.content||m.text||'',m.role==='user');})().catch(e=>UI.toast(e.message,true));
})();
