'use strict';
(()=>{
 const $=id=>document.getElementById(id),screen=$('screen'),mask=$('mask'),canvas=$('edit'),ctx=canvas.getContext('2d'),mctx=mask.getContext('2d');
 let region=null,origin=null,tool='rect',commands=[],draft=null,base=null,busy=false,textPoint=null,noticeTimer;
 const tools=[['rect','矩形','<rect x="4" y="5" width="16" height="14" rx="2"/>'],['ellipse','画圈','<ellipse cx="12" cy="12" rx="9" ry="8"/>'],['line','划线','<path d="M4 19L20 5"/>'],['arrow','箭头','<path d="M4 20L20 4M8 4h12v12"/>'],['pen','画笔','<path d="M4 20l4-1L20 7l-3-3L5 16z"/>'],['text','标注文字','<path d="M4 6V4h16v2M12 4v16M8 20h8"/>'],['mosaic','马赛克','<rect x="4" y="4" width="16" height="16"/><path d="M4 9h16M4 15h16M9 4v16M15 4v16"/>']];
 for(const [id,label,svg]of tools){const b=document.createElement('button');b.dataset.tool=id;b.title=label;b.setAttribute('aria-label',label);b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+svg+'</svg>';b.onclick=()=>{tool=id;updateTools();$('menu').hidden=true;};$('draw-tools').append(b);}
 function updateTools(){document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===tool);b.setAttribute('aria-pressed',String(b.dataset.tool===tool));});canvas.style.cursor=tool==='text'?'text':tool==='pick'?'copy':'crosshair';}
 function notice(t){clearTimeout(noticeTimer);$('status').textContent=t;$('status').hidden=false;noticeTimer=setTimeout(()=>$('status').hidden=true,5000);}
 function rect(a,b){return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)};}
 const pointer=e=>({x:Math.max(0,Math.min(innerWidth,e.clientX)),y:Math.max(0,Math.min(innerHeight,e.clientY))});
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width-1,(e.clientX-r.x)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height-1,(e.clientY-r.y)*canvas.height/r.height))};};
 function shade(){mask.width=innerWidth;mask.height=innerHeight;mctx.fillStyle='#101a2c70';mctx.fillRect(0,0,mask.width,mask.height);if(region){mctx.clearRect(region.x,region.y,region.w,region.h);mctx.strokeStyle='#8baada';mctx.lineWidth=1;mctx.strokeRect(region.x+.5,region.y+.5,region.w-1,region.h-1);$('size').hidden=false;$('size').textContent=Math.round(region.w*screen.naturalWidth/innerWidth)+' × '+Math.round(region.h*screen.naturalHeight/innerHeight);$('size').style.left=Math.max(8,region.x)+'px';$('size').style.top=Math.max(8,region.y-31)+'px';}}
 function position(el,preferredY){el.style.left=Math.min(innerWidth-el.offsetWidth-8,Math.max(8,region?.x||20))+'px';el.style.top=Math.max(8,Math.min(innerHeight-el.offsetHeight-8,preferredY))+'px';}
 function choose(){if(!region||region.w<6||region.h<6){region=null;shade();return;}const sx=screen.naturalWidth/innerWidth,sy=screen.naturalHeight/innerHeight;base=document.createElement('canvas');base.width=Math.round(region.w*sx);base.height=Math.round(region.h*sy);base.getContext('2d').drawImage(screen,region.x*sx,region.y*sy,region.w*sx,region.h*sy,0,0,base.width,base.height);canvas.width=base.width;canvas.height=base.height;Object.assign(canvas.style,{left:region.x+'px',top:region.y+'px',width:region.w+'px',height:region.h+'px'});canvas.hidden=false;commands=[];paint();$('toolbar').hidden=false;position($('toolbar'),region.y+region.h+8);$('hint').hidden=true;void capture.select();}
 function draw(c){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=c.color;ctx.fillStyle=c.color;ctx.lineWidth=c.weight;const a=c.points[0],b=c.points.at(-1),r=rect(a,b);
  if(c.kind==='mosaic'){const x=Math.floor(r.x),y=Math.floor(r.y),w=Math.min(canvas.width-x,Math.ceil(r.w)),h=Math.min(canvas.height-y,Math.ceil(r.h));if(w>0&&h>0){const tiny=document.createElement('canvas');tiny.width=Math.max(1,Math.ceil(w/14));tiny.height=Math.max(1,Math.ceil(h/14));tiny.getContext('2d').drawImage(canvas,x,y,w,h,0,0,tiny.width,tiny.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(tiny,0,0,tiny.width,tiny.height,x,y,w,h);}}
  else if(c.kind==='text'){ctx.font=c.font+'px "HarmonyOS Sans SC","Microsoft YaHei",sans-serif';ctx.textBaseline='top';String(c.text).split('\n').forEach((line,i)=>ctx.fillText(line,a.x,a.y+i*c.font*1.4));}
  else if(c.kind==='translation'){for(const r of c.regions){const x=r.x*canvas.width/1000,y=r.y*canvas.height/1000,w=Math.min(canvas.width-x,r.w*canvas.width/1000),h=Math.min(canvas.height-y,r.h*canvas.height/1000);const font=Math.max(12,Math.min(36,h*.65));ctx.fillStyle='#fffffff5';ctx.fillRect(x,y,w,h);ctx.fillStyle='#26323d';ctx.font=font+'px "HarmonyOS Sans SC","Microsoft YaHei",sans-serif';ctx.textBaseline='top';let line='',row=0;for(const ch of r.text){if(ctx.measureText(line+ch).width>w-6&&line){ctx.fillText(line,x+3,y+row*font*1.2,w-6);line='';row++;}line+=ch;}ctx.fillText(line,x+3,y+row*font*1.2,w-6);}}
  else{ctx.beginPath();if(c.kind==='rect')ctx.rect(r.x,r.y,r.w,r.h);else if(c.kind==='ellipse')ctx.ellipse(r.x+r.w/2,r.y+r.h/2,Math.max(.1,r.w/2),Math.max(.1,r.h/2),0,0,Math.PI*2);else{ctx.moveTo(a.x,a.y);for(const p of c.points.slice(1))ctx.lineTo(p.x,p.y);}ctx.stroke();if(c.kind==='arrow'){const angle=Math.atan2(b.y-a.y,b.x-a.x),length=Math.max(12,c.weight*4);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-length*Math.cos(angle-.45),b.y-length*Math.sin(angle-.45));ctx.lineTo(b.x-length*Math.cos(angle+.45),b.y-length*Math.sin(angle+.45));ctx.closePath();ctx.fill();}}
  ctx.restore();
 }
 function paint(){if(!base)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(base,0,0);for(const c of commands)draw(c);if(draft)draw(draft);$('undo').disabled=!commands.length;}
 mask.onpointerdown=e=>{if(e.button!==0||busy)return;origin=pointer(e);region=rect(origin,origin);mask.setPointerCapture(e.pointerId);};mask.onpointermove=e=>{if(origin){region=rect(origin,pointer(e));shade();}};mask.onpointerup=e=>{if(!origin)return;region=rect(origin,pointer(e));origin=null;shade();choose();};mask.onpointercancel=()=>{origin=null;};
 canvas.onpointerdown=e=>{if(e.button!==0||busy)return;$('menu').hidden=true;const p=point(e);if(tool==='pick'){const pixel=ctx.getImageData(Math.floor(p.x),Math.floor(p.y),1,1).data,hex='#'+[...pixel].slice(0,3).map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();capture.copyText(hex).then(()=>notice('已复制 '+hex)).catch(e=>notice(e.message));return;}if(tool==='text'){textPoint=p;const input=$('annotation');input.value='';input.hidden=false;input.style.left=Math.min(innerWidth-170,e.clientX)+'px';input.style.top=Math.min(innerHeight-70,e.clientY)+'px';input.style.color=$('color').value;input.focus();return;}draft={kind:tool,color:$('color').value,weight:+$('weight').value*canvas.width/region.w,points:[p,p]};canvas.setPointerCapture(e.pointerId);};
 canvas.onpointermove=e=>{if(!draft)return;const p=point(e);if(tool==='pen')draft.points.push(p);else draft.points[1]=p;paint();};canvas.onpointerup=()=>{if(draft){commands.push(draft);draft=null;paint();}};canvas.onpointercancel=()=>{draft=null;paint();};
 function finishText(){if(!textPoint)return;const t=$('annotation').value.trim();if(t)commands.push({kind:'text',color:$('color').value,font:(+$('weight').value+15)*canvas.width/region.w,points:[textPoint],text:t});textPoint=null;$('annotation').hidden=true;paint();}$('annotation').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();finishText();}if(e.key==='Escape'){textPoint=null;$('annotation').hidden=true;e.stopPropagation();}};$('annotation').onblur=finishText;
 function output(){finishText();return canvas.toDataURL('image/png');}
 async function task(fn){if(busy)return;busy=true;document.querySelectorAll('#toolbar button').forEach(b=>b.disabled=true);$('cancel').disabled=false;notice('正在处理…');try{await fn();}catch(e){notice(e.message||'处理失败，请重试');}finally{busy=false;document.querySelectorAll('#toolbar button').forEach(b=>b.disabled=false);$('undo').disabled=!commands.length;}}
 function menu(items){const box=$('menu');box.replaceChildren();for(const [label,fn]of items){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{box.hidden=true;fn();};box.append(b);}box.hidden=false;position(box,parseFloat($('toolbar').style.top)+$('toolbar').offsetHeight+8);}
 function showResult(title,text){$('result-title').textContent=title;$('result-text').value=text;$('result-text').hidden=false;$('swatches').hidden=true;$('result-copy').hidden=false;$('result-note').textContent='可编辑后复制';$('result').hidden=false;position($('result'),region.y+30);}
 $('recognize').onclick=()=>menu([['提取文字',()=>extract('text','文字')],['提取并清洗',()=>extract('clean','清洗结果')],['提取表格 · 保留行列',()=>extract('table','表格')],['提取公式 · LaTeX',()=>extract('formula','公式')]]);
 function extract(kind,title){void task(async()=>{const text=await capture.extract({image:output(),kind});showResult(title,text);notice('提取完成，可复制或继续编辑截图');});}
 $('translate').onclick=()=>menu(['简体中文','English','日本語','한국어'].map(language=>[language,()=>task(async()=>{const r=await capture.extract({image:output(),kind:'translate',language});if(!r.regions.length)throw Error('没有可翻译的文字');commands.push({kind:'translation',regions:r.regions,points:[{x:0,y:0}]});paint();notice('翻译已覆盖到图片，可撤销、保存或复制');})]));
 $('palette').onclick=()=>{tool='pick';updateTools();const {data}=ctx.getImageData(0,0,canvas.width,canvas.height),counts=new Map(),step=Math.max(4,Math.floor(data.length/10000/4)*4);for(let i=0;i<data.length;i+=step){const rgb=[data[i],data[i+1],data[i+2]].map(v=>Math.min(255,Math.round(v/24)*24));const hex='#'+rgb.map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();counts.set(hex,(counts.get(hex)||0)+1);}const colors=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]);$('result-title').textContent='图片色值';$('result-text').hidden=true;$('swatches').hidden=false;$('swatches').replaceChildren();for(const hex of colors){const b=document.createElement('button');b.textContent=hex;b.style.background='linear-gradient('+hex+' 0 22px,white 22px)';b.onclick=()=>capture.copyText(hex).then(()=>notice('已复制 '+hex));$('swatches').append(b);}$('result-copy').hidden=true;$('result-note').textContent='点击色卡复制 · 点击图片提取精确像素色';$('result').hidden=false;position($('result'),region.y+30);};
 $('undo').onclick=()=>{commands.pop();paint();};$('result-close').onclick=()=>$('result').hidden=true;$('result-copy').onclick=()=>capture.copyText($('result-text').value).then(()=>notice('已复制提取结果')).catch(e=>notice(e.message));
 $('cancel').onclick=()=>capture.cancel();$('done').onclick=()=>task(async()=>{const r=await capture.commit(output());if(r.status==='large')notice('截图已复制，图片过大未加入历史');});$('save').onclick=()=>task(async()=>{if(await capture.save(output()))notice('已保存到本地');});
 $('reselect').onclick=()=>{region=null;base=null;commands=[];canvas.hidden=true;for(const id of ['toolbar','result','menu','size'])$(id).hidden=true;$('hint').hidden=false;shade();};
 document.onkeydown=e=>{if(e.key==='Escape'){void capture.cancel();return;}if(e.target.matches('textarea,input,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();commands.pop();paint();}if(e.key==='Enter'&&base&&!busy)$('done').click();};
 updateTools();capture.init().then(data=>{screen.onload=shade;screen.src=data.image;}).catch(e=>notice(e.message));
})();

