'use strict';
const { contextBridge, ipcRenderer } = require('electron');

/** 工作栏桥：仅白名单方法，参数在主进程校验。 */
contextBridge.exposeInMainWorld('api', {
  soundscapeState:()=>ipcRenderer.invoke('soundscape:state'),
  soundscapeCommand:data=>ipcRenderer.invoke('soundscape:command',data),
  onSoundscapeChanged:cb=>ipcRenderer.on('soundscape:changed',(_e,value)=>cb(value)),
  studyState:()=>ipcRenderer.invoke('study:state'),
  studyConnect:()=>ipcRenderer.invoke('study:connect'),
  studyDisconnect:()=>ipcRenderer.invoke('study:disconnect'),
  studySync:()=>ipcRenderer.invoke('study:sync'),
  studyResolve:choice=>ipcRenderer.invoke('study:resolve',choice),
  studyTask:data=>ipcRenderer.invoke('study:task',data),
  studyCard:id=>ipcRenderer.invoke('study:card',id),
  studyPrompt:kind=>ipcRenderer.invoke('study:prompt',kind),
  studyWebsite:()=>ipcRenderer.invoke('study:website'),
  onStudyChanged:cb=>ipcRenderer.on('study:changed',(_e,value)=>cb(value)),
  // 设置
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  setSecret: (name, value) => ipcRenderer.invoke('secrets:set', { name, value }),
  hasSecret: (name) => ipcRenderer.invoke('secrets:has', name),
  hotkeyStatus: () => ipcRenderer.invoke('hotkeys:status'),
  systemState: () => ipcRenderer.invoke('system:state'),
  createDesktopShortcut: () => ipcRenderer.invoke('system:shortcut'),
  clipboardJobStatus: () => ipcRenderer.invoke('clipboard:jobStatus'),
  clipboardRunQuick: (kind) => ipcRenderer.invoke('clipboard:runQuick', kind),
  toolboxState: () => ipcRenderer.invoke('toolbox:state'),
  toolboxCapture: () => ipcRenderer.invoke('toolbox:capture'),
  toolboxClipEdit: (id, action) => ipcRenderer.invoke('toolbox:clipEdit', { id, action }),
  toolboxClearClips: () => ipcRenderer.invoke('toolbox:clearClips'),
  toolboxCopyClip: (id) => ipcRenderer.invoke('toolbox:copyClip', id),
  toolboxSaveNote: (data) => ipcRenderer.invoke('toolbox:saveNote', data),
  toolboxDeleteNote: (id) => ipcRenderer.invoke('toolbox:deleteNote', id),
  toolboxExportNotes: () => ipcRenderer.invoke('toolbox:exportNotes'),
  toolboxSavePalette: (data) => ipcRenderer.invoke('toolbox:savePalette', data),
  toolboxDeletePalette: (id) => ipcRenderer.invoke('toolbox:deletePalette', id),
  onToolboxChanged: (cb) => ipcRenderer.on('toolbox:changed', (_e, value) => cb(value)),
  // 窗口
  hideWorkbar: () => ipcRenderer.invoke('workbar:hide'),
  // 问答
  chatSend: (text) => ipcRenderer.invoke('chat:send', { text }),
  chatStop: () => ipcRenderer.invoke('chat:stop'),
  chatHistory: () => ipcRenderer.invoke('chat:history'),
  chatClear: () => ipcRenderer.invoke('chat:clear'),
  llmTest: () => ipcRenderer.invoke('llm:test'),
  llmConfigured: () => ipcRenderer.invoke('llm:configured'),
  llmProofread: (text) => ipcRenderer.invoke('llm:proofread', { text }),
  onChatDelta: (cb) => ipcRenderer.on('chat:delta', (_e, d) => cb(d)),
  // 文本处理
  textRules: () => ipcRenderer.invoke('text:rules'),
  textApply: (text, rules) => ipcRenderer.invoke('text:apply', { text, rules }),
  clipboardSnapshot: () => ipcRenderer.invoke('clipboard:snapshot'),
  clipboardWriteText: (t) => ipcRenderer.invoke('clipboard:writeText', t),
  onProcessLoad: (cb) => ipcRenderer.on('process:load', (_e, t) => cb(t)),
  // OCR
  ocrRecognize: (dataUrl, lang) => ipcRenderer.invoke('ocr:recognize', { dataUrl, lang }),
  onOcrLoadImage: (cb) => ipcRenderer.on('ocr:loadImage', (_e, d) => cb(d)),
  // Agents
  agentsSnapshot: () => ipcRenderer.invoke('agents:snapshot'),
  limitsRefresh: () => ipcRenderer.invoke('limits:refresh'),
  limitsStatus: () => ipcRenderer.invoke('limits:status'),
  onLimitsStatus: (cb) => ipcRenderer.on('limits:status', (_e, value) => cb(value)),
  onAgentsSnapshot: (cb) => ipcRenderer.on('agents:snapshot', (_e, s) => cb(s)),
  // 用量
  usageAggregate: () => ipcRenderer.invoke('usage:aggregate'),
  usagePrune: () => ipcRenderer.invoke('usage:prune'),
  usageExport: () => ipcRenderer.invoke('usage:export'),
  onUsageUpdated: (cb) => ipcRenderer.on('usage:updated', (_e, u) => cb(u)),
  // 日程
  calendarView: () => ipcRenderer.invoke('calendar:view'),
  calendarAdd: (item) => ipcRenderer.invoke('calendar:addLocal', item),
  calendarRemove: (source, externalId) => ipcRenderer.invoke('calendar:remove', { source, externalId }),
  calendarSyncNotion: () => ipcRenderer.invoke('calendar:syncNotion'),
  calendarNotionStatus: () => ipcRenderer.invoke('calendar:notionStatus'),
  focusState: () => ipcRenderer.invoke('focus:state'),
  focusStats: () => ipcRenderer.invoke('focus:stats'),
  focusStart: (data) => ipcRenderer.invoke('focus:start', data),
  focusPause: () => ipcRenderer.invoke('focus:pause'),
  focusResume: () => ipcRenderer.invoke('focus:resume'),
  focusStop: () => ipcRenderer.invoke('focus:stop'),
  focusAddLabel: (data) => ipcRenderer.invoke('focus:addLabel', data),
  onFocusChanged: (cb) => ipcRenderer.on('focus:changed', (_e, value) => cb(value)),
  onFocusTick: (cb) => ipcRenderer.on('focus:tick', (_e, value) => cb(value)),
  onPetConfig: (cb) => ipcRenderer.on('pet:config', (_e, value) => cb(value)),
  onCalendarChanged: (cb) => ipcRenderer.on('calendar:changed', (_e, v) => cb(v)),
  onCalendarFired: (cb) => ipcRenderer.on('calendar:fired', (_e, v) => cb(v)),
  onCalendarSyncResult: (cb) => ipcRenderer.on('calendar:syncResult', (_e, v) => cb(v)),
  // 宠物状态（工作栏头部展示）
  onPetState: (cb) => ipcRenderer.on('pet:state', (_e, s) => cb(s)),
  // 页签跳转（如提醒点击 → 日程页）
  onNavigate: (cb) => ipcRenderer.on('workbar:navigate', (_e, tab) => cb(tab)),
  // 通用
  openExternal: (url) => ipcRenderer.invoke('sys:openExternal', url),
  getPets: () => ipcRenderer.invoke('pets:list'),
  setListening: (on) => ipcRenderer.send('ui:setListening', on),
});
