'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');

/** 工作栏桥：仅白名单方法，参数在主进程校验。 */
contextBridge.exposeInMainWorld('api', {
  fileSearch:q=>ipcRenderer.invoke('files:search',q),fileContext:ids=>ipcRenderer.invoke('files:context',ids),fileDrag:id=>ipcRenderer.send('files:drag',id),
  fileLibrary:()=>ipcRenderer.invoke('files:state'),fileCreate:data=>ipcRenderer.invoke('files:create',data),fileResolve:data=>ipcRenderer.invoke('files:resolve',data),fileImport:files=>ipcRenderer.invoke('files:import',files),fileImportDrop:data=>ipcRenderer.invoke('files:importDrop',data),fileSelect:()=>ipcRenderer.invoke('files:select'),fileOpen:id=>ipcRenderer.invoke('files:open',id),fileRoot:()=>ipcRenderer.invoke('files:root'),filePath:file=>webUtils.getPathForFile(file),
  islandHit:rects=>ipcRenderer.send('island:hit',rects),onIslandHitRefresh:cb=>ipcRenderer.on('island:hitRefresh',()=>cb()),onIslandNavigate:cb=>ipcRenderer.on('island:navigate',(_e,tab)=>cb(tab)),onIslandIdle:cb=>ipcRenderer.on('island:idle',(_e,idle)=>cb(idle)),
  islandInputFocus:()=>ipcRenderer.invoke('island:inputFocus'),
  islandHide:()=>ipcRenderer.invoke('island:hide'),islandLeave:()=>ipcRenderer.invoke('island:leave'),islandHover:on=>ipcRenderer.send('island:hover',on),
  islandQuickChat:text=>ipcRenderer.invoke('quick:chat',text),onIslandReply:cb=>ipcRenderer.on('island:reply',(_e,value)=>cb(value)),islandReplyClose:()=>ipcRenderer.send('island:replyClose'),
  islandResize:height=>ipcRenderer.invoke('island:resize',height),
  islandDismissNotice:id=>ipcRenderer.invoke('island:dismissNotice',id),
  islandReveal:()=>ipcRenderer.invoke('island:reveal'),islandState:()=>ipcRenderer.invoke('island:state'),
  islandMode:mode=>ipcRenderer.invoke('island:mode',mode),
  islandExpand:on=>ipcRenderer.invoke('island:expand',on),
  islandWorkbar:tab=>ipcRenderer.invoke('island:workbar',tab),
  islandPills:pills=>ipcRenderer.invoke('island:pills',pills),
  onIslandChanged:cb=>ipcRenderer.on('island:changed',(_e,data)=>cb(data)),
  onIslandExpanded:cb=>ipcRenderer.on('island:expanded',(_e,on)=>cb(on)),
  integrationsSave:data=>ipcRenderer.invoke('integrations:save',data),
  integrationsDisconnect:id=>ipcRenderer.invoke('integrations:disconnect',id),
  integrationsRefresh:id=>ipcRenderer.invoke('integrations:refresh',id),
  integrationsGithubLocal:()=>ipcRenderer.invoke('integrations:githubLocal'),
  hooksPreview:(source,remove=false)=>ipcRenderer.invoke('hooks:preview',source,remove),
  hooksApply:data=>ipcRenderer.invoke('hooks:apply',data),
  hooksResolve:data=>ipcRenderer.invoke('hooks:resolve',data),
  hooksClearRules:()=>ipcRenderer.invoke('hooks:clearRules'),
  agentTerminal:key=>ipcRenderer.invoke('agents:terminal',key),
  musicCommand:command=>ipcRenderer.invoke('music:command',command),
  musicConfig:data=>ipcRenderer.invoke('music:config',data),
  musicOpen:()=>ipcRenderer.invoke('music:open'),
  islandDropFile:()=>ipcRenderer.invoke('island:dropFile'),
  workbarScene:tab=>ipcRenderer.send('workbar:scene',tab),
  voiceState:()=>ipcRenderer.invoke('voice:state'),voiceDevices:()=>ipcRenderer.invoke('voice:devices'),voiceConfig:()=>ipcRenderer.invoke('voice:config'),voiceSave:config=>ipcRenderer.invoke('voice:save',config),
  voiceDownload:()=>ipcRenderer.invoke('voice:download'),voiceDownloadCancel:()=>ipcRenderer.invoke('voice:downloadCancel'),
  voicePause:()=>ipcRenderer.invoke('voice:pause'),voiceFinish:()=>ipcRenderer.invoke('voice:finish'),voiceCancel:()=>ipcRenderer.invoke('voice:cancel'),voiceCopy:()=>ipcRenderer.invoke('voice:copy'),
  voiceHotwordTest:(text,config)=>ipcRenderer.invoke('voice:hotwordTest',{text,config}),voiceExport:()=>ipcRenderer.invoke('voice:export'),voiceTestLlm:()=>ipcRenderer.invoke('voice:testLlm'),
  onVoiceChanged:cb=>ipcRenderer.on('voice:changed',(_e,value)=>cb(value)),
  voiceStats:()=>ipcRenderer.invoke('voice:stats'),onVoiceConfigChanged:cb=>ipcRenderer.on('voice:configChanged',(_e,value)=>cb(value)),
  onVoiceStatsChanged:cb=>ipcRenderer.on('voice:statsChanged',(_e,value)=>cb(value)),
  soundscapeState:()=>ipcRenderer.invoke('soundscape:state'),
  soundscapeCommand:data=>ipcRenderer.invoke('soundscape:command',data),
  onSoundscapeChanged:cb=>ipcRenderer.on('soundscape:changed',(_e,value)=>cb(value)),
  // 设置
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  setSecret: (name, value) => ipcRenderer.invoke('secrets:set', { name, value }),
  hasSecret: (name) => ipcRenderer.invoke('secrets:has', name),
  hotkeyStatus: () => ipcRenderer.invoke('hotkeys:status'),
  systemState: () => ipcRenderer.invoke('system:state'),
  createDesktopShortcut: () => ipcRenderer.invoke('system:shortcut'),
  clipboardJobStatus: () => ipcRenderer.invoke('clipboard:jobStatus'),
  clipboardRunQuick: (kind) => ipcRenderer.invoke('clipboard:runQuick', kind),
  toolboxState: () => ipcRenderer.invoke('toolbox:state'),
  toolboxCapture: () => ipcRenderer.invoke('toolbox:capture'),
  toolboxClipEdit: (id, action) => ipcRenderer.invoke('toolbox:clipEdit', { id, action }),
  toolboxClearClips: () => ipcRenderer.invoke('toolbox:clearClips'),
  toolboxCopyClip: (id) => ipcRenderer.invoke('toolbox:copyClip', id),
  toolboxSaveNote: (data) => ipcRenderer.invoke('toolbox:saveNote', data),
  toolboxDeleteNote: (id) => ipcRenderer.invoke('toolbox:deleteNote', id),
  toolboxExportNotes: () => ipcRenderer.invoke('toolbox:exportNotes'),
  toolboxSavePalette: (data) => ipcRenderer.invoke('toolbox:savePalette', data),
  toolboxDeletePalette: (id) => ipcRenderer.invoke('toolbox:deletePalette', id),
  onToolboxChanged: (cb) => ipcRenderer.on('toolbox:changed', (_e, value) => cb(value)),
  // 窗口
  hideWorkbar: () => ipcRenderer.invoke('workbar:hide'),
  // 问答
  chatSend: (text,fileIds=[]) => ipcRenderer.invoke('chat:send', { text,fileIds }),
  chatStop: () => ipcRenderer.invoke('chat:stop'),
  chatHistory: () => ipcRenderer.invoke('chat:history'),
  chatClear: () => ipcRenderer.invoke('chat:clear'),
  llmTest: () => ipcRenderer.invoke('llm:test'),
  llmConfigured: () => ipcRenderer.invoke('llm:configured'),
  llmProofread: (text) => ipcRenderer.invoke('llm:proofread', { text }),
  onChatDelta: (cb) => ipcRenderer.on('chat:delta', (_e, d) => cb(d)),
  // 文本处理
  textRules: () => ipcRenderer.invoke('text:rules'),
  textApply: (text, rules, options = {}) => ipcRenderer.invoke('text:apply', { text, rules, id:options.id, source:options.source }),
  textCleanStatus: () => ipcRenderer.invoke('text:status'),
  textCancel: (id) => ipcRenderer.invoke('text:cancel', id),
  onTextDelta: (cb) => ipcRenderer.on('text:delta', (_e, data) => cb(data)),
  clipboardSnapshot: () => ipcRenderer.invoke('clipboard:snapshot'),
  clipboardWriteText: (t) => ipcRenderer.invoke('clipboard:writeText', t),
  onProcessLoad: (cb) => ipcRenderer.on('process:load', (_e, t) => cb(t)),
  // OCR
  ocrRecognize: (dataUrl, lang) => ipcRenderer.invoke('ocr:recognize', { dataUrl, lang }),
  onOcrLoadImage: (cb) => ipcRenderer.on('ocr:loadImage', (_e, d) => cb(d)),
  // Agents
  agentsSnapshot: () => ipcRenderer.invoke('agents:snapshot'),
  limitsRefresh: () => ipcRenderer.invoke('limits:refresh'),
  limitsStatus: () => ipcRenderer.invoke('limits:status'),
  onLimitsStatus: (cb) => ipcRenderer.on('limits:status', (_e, value) => cb(value)),
  onAgentsSnapshot: (cb) => ipcRenderer.on('agents:snapshot', (_e, s) => cb(s)),
  // 用量
  usageAggregate: () => ipcRenderer.invoke('usage:aggregate'),
  usagePrune: () => ipcRenderer.invoke('usage:prune'),
  usageExport: () => ipcRenderer.invoke('usage:export'),
  onUsageUpdated: (cb) => ipcRenderer.on('usage:updated', (_e, u) => cb(u)),
  // 日程
  calendarView: () => ipcRenderer.invoke('calendar:view'),
  calendarAdd: (item) => ipcRenderer.invoke('calendar:addLocal', item),
  calendarRemove: (source, externalId) => ipcRenderer.invoke('calendar:remove', { source, externalId }),
  calendarSyncNotion: () => ipcRenderer.invoke('calendar:syncNotion'),
  calendarNotionStatus: () => ipcRenderer.invoke('calendar:notionStatus'),
  focusState: () => ipcRenderer.invoke('focus:state'),
  focusStats: () => ipcRenderer.invoke('focus:stats'),
  focusStart: (data) => ipcRenderer.invoke('focus:start', data),
  focusPause: () => ipcRenderer.invoke('focus:pause'),
  focusResume: () => ipcRenderer.invoke('focus:resume'),
  focusStop: () => ipcRenderer.invoke('focus:stop'),
  focusAddLabel: (data) => ipcRenderer.invoke('focus:addLabel', data),
  onFocusChanged: (cb) => ipcRenderer.on('focus:changed', (_e, value) => cb(value)),
  onFocusTick: (cb) => ipcRenderer.on('focus:tick', (_e, value) => cb(value)),
  onPetConfig: (cb) => ipcRenderer.on('pet:config', (_e, value) => cb(value)),
  onCalendarChanged: (cb) => ipcRenderer.on('calendar:changed', (_e, v) => cb(v)),
  onCalendarFired: (cb) => ipcRenderer.on('calendar:fired', (_e, v) => cb(v)),
  onCalendarSyncResult: (cb) => ipcRenderer.on('calendar:syncResult', (_e, v) => cb(v)),
  // 宠物状态（工作栏头部展示）
  onPetState: (cb) => ipcRenderer.on('pet:state', (_e, s) => cb(s)),
  // 页签跳转（如提醒点击 → 日程页）
  onNavigate: (cb) => ipcRenderer.on('workbar:navigate', (_e, tab) => cb(tab)),
  // 通用
  openExternal: (url) => ipcRenderer.invoke('sys:openExternal', url),
  getPets: () => ipcRenderer.invoke('pets:list'),
  setListening: (on) => ipcRenderer.send('ui:setListening', on),
});
